// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      2026-01-27
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*
// @match        https://*.google.com/*
// @match        http://*.skazanie.com/*
// @match        http://*.bbgam.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=google.com
// @grant        GM_xmlhttpRequest
// ==/UserScript==

(function () {
    'use strict';

    // 1. ВСТАВЬТЕ СЮДА СОДЕРЖИМОЕ ФАЙЛА pkg/your_project.js
    // (Скопируйте всё из .js файла, сгенерированного wasm-pack --target no-modules)
    let wasm_bindgen = (function (exports) {
        let script_src;
        if (typeof document !== 'undefined' && document.currentScript !== null) {
            script_src = new URL(document.currentScript.src, location.href).toString();
        }

        /**
         * @param {string} name
         * @returns {string}
         */
        function greet(name) {
            let deferred2_0;
            let deferred2_1;
            try {
                const ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
                const len0 = WASM_VECTOR_LEN;
                const ret = wasm.greet(ptr0, len0);
                deferred2_0 = ret[0];
                deferred2_1 = ret[1];
                return getStringFromWasm0(ret[0], ret[1]);
            } finally {
                wasm.__wbindgen_free(deferred2_0, deferred2_1, 1);
            }
        }
        exports.greet = greet;

        function greet_and_log() {
            wasm.greet_and_log();
        }
        exports.greet_and_log = greet_and_log;

        function __wbg_get_imports() {
            const import0 = {
                __proto__: null,
                __wbg___wbindgen_is_undefined_9e4d92534c42d778: function (arg0) {
                    const ret = arg0 === undefined;
                    return ret;
                },
                __wbg___wbindgen_throw_be289d5034ed271b: function (arg0, arg1) {
                    throw new Error(getStringFromWasm0(arg0, arg1));
                },
                __wbg_call_389efe28435a9388: function () {
                    return handleError(function (arg0, arg1) {
                        const ret = arg0.call(arg1);
                        return ret;
                    }, arguments);
                },
                __wbg_error_7534b8e9a36f1ab4: function (arg0, arg1) {
                    let deferred0_0;
                    let deferred0_1;
                    try {
                        deferred0_0 = arg0;
                        deferred0_1 = arg1;
                        console.error(getStringFromWasm0(arg0, arg1));
                    } finally {
                        wasm.__wbindgen_free(deferred0_0, deferred0_1, 1);
                    }
                },
                __wbg_instanceof_Window_ed49b2db8df90359: function (arg0) {
                    let result;
                    try {
                        result = arg0 instanceof Window;
                    } catch (_) {
                        result = false;
                    }
                    const ret = result;
                    return ret;
                },
                __wbg_log_6b5ca2e6124b2808: function (arg0) {
                    console.log(arg0);
                },
                __wbg_new_8a6f238a6ece86ea: function () {
                    const ret = new Error();
                    return ret;
                },
                __wbg_new_no_args_1c7c842f08d00ebb: function (arg0, arg1) {
                    const ret = new Function(getStringFromWasm0(arg0, arg1));
                    return ret;
                },
                __wbg_stack_0ed75d68575b0f3c: function (arg0, arg1) {
                    const ret = arg1.stack;
                    const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
                    const len1 = WASM_VECTOR_LEN;
                    getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
                    getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
                },
                __wbg_static_accessor_GLOBAL_12837167ad935116: function () {
                    const ret = typeof global === 'undefined' ? null : global;
                    return isLikeNone(ret) ? 0 : addToExternrefTable0(ret);
                },
                __wbg_static_accessor_GLOBAL_THIS_e628e89ab3b1c95f: function () {
                    const ret = typeof globalThis === 'undefined' ? null : globalThis;
                    return isLikeNone(ret) ? 0 : addToExternrefTable0(ret);
                },
                __wbg_static_accessor_SELF_a621d3dfbb60d0ce: function () {
                    const ret = typeof self === 'undefined' ? null : self;
                    return isLikeNone(ret) ? 0 : addToExternrefTable0(ret);
                },
                __wbg_static_accessor_WINDOW_f8727f0cf888e0bd: function () {
                    const ret = typeof window === 'undefined' ? null : window;
                    return isLikeNone(ret) ? 0 : addToExternrefTable0(ret);
                },
                __wbg_timeEnd_4b7c4393c92f755c: function (arg0, arg1) {
                    console.timeEnd(getStringFromWasm0(arg0, arg1));
                },
                __wbg_time_fe7e4750af05fa96: function (arg0, arg1) {
                    console.time(getStringFromWasm0(arg0, arg1));
                },
                __wbindgen_cast_0000000000000001: function (arg0, arg1) {
                    // Cast intrinsic for `Ref(String) -> Externref`.
                    const ret = getStringFromWasm0(arg0, arg1);
                    return ret;
                },
                __wbindgen_init_externref_table: function () {
                    const table = wasm.__wbindgen_externrefs;
                    const offset = table.grow(4);
                    table.set(0, undefined);
                    table.set(offset + 0, undefined);
                    table.set(offset + 1, null);
                    table.set(offset + 2, true);
                    table.set(offset + 3, false);
                },
            };
            return {
                __proto__: null,
                "./wasm_bg.js": import0,
            };
        }

        function addToExternrefTable0(obj) {
            const idx = wasm.__externref_table_alloc();
            wasm.__wbindgen_externrefs.set(idx, obj);
            return idx;
        }

        let cachedDataViewMemory0 = null;
        function getDataViewMemory0() {
            if (cachedDataViewMemory0 === null || cachedDataViewMemory0.buffer.detached === true || (cachedDataViewMemory0.buffer.detached === undefined && cachedDataViewMemory0.buffer !== wasm.memory.buffer)) {
                cachedDataViewMemory0 = new DataView(wasm.memory.buffer);
            }
            return cachedDataViewMemory0;
        }

        function getStringFromWasm0(ptr, len) {
            ptr = ptr >>> 0;
            return decodeText(ptr, len);
        }

        let cachedUint8ArrayMemory0 = null;
        function getUint8ArrayMemory0() {
            if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
                cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
            }
            return cachedUint8ArrayMemory0;
        }

        function handleError(f, args) {
            try {
                return f.apply(this, args);
            } catch (e) {
                const idx = addToExternrefTable0(e);
                wasm.__wbindgen_exn_store(idx);
            }
        }

        function isLikeNone(x) {
            return x === undefined || x === null;
        }

        function passStringToWasm0(arg, malloc, realloc) {
            if (realloc === undefined) {
                const buf = cachedTextEncoder.encode(arg);
                const ptr = malloc(buf.length, 1) >>> 0;
                getUint8ArrayMemory0().subarray(ptr, ptr + buf.length).set(buf);
                WASM_VECTOR_LEN = buf.length;
                return ptr;
            }

            let len = arg.length;
            let ptr = malloc(len, 1) >>> 0;

            const mem = getUint8ArrayMemory0();

            let offset = 0;

            for (; offset < len; offset++) {
                const code = arg.charCodeAt(offset);
                if (code > 0x7F) break;
                mem[ptr + offset] = code;
            }
            if (offset !== len) {
                if (offset !== 0) {
                    arg = arg.slice(offset);
                }
                ptr = realloc(ptr, len, len = offset + arg.length * 3, 1) >>> 0;
                const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
                const ret = cachedTextEncoder.encodeInto(arg, view);

                offset += ret.written;
                ptr = realloc(ptr, len, offset, 1) >>> 0;
            }

            WASM_VECTOR_LEN = offset;
            return ptr;
        }

        let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
        cachedTextDecoder.decode();
        function decodeText(ptr, len) {
            return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
        }

        const cachedTextEncoder = new TextEncoder();

        if (!('encodeInto' in cachedTextEncoder)) {
            cachedTextEncoder.encodeInto = function (arg, view) {
                const buf = cachedTextEncoder.encode(arg);
                view.set(buf);
                return {
                    read: arg.length,
                    written: buf.length
                };
            };
        }

        let WASM_VECTOR_LEN = 0;

        let wasmModule, wasm;
        function __wbg_finalize_init(instance, module) {
            wasm = instance.exports;
            wasmModule = module;
            cachedDataViewMemory0 = null;
            cachedUint8ArrayMemory0 = null;
            wasm.__wbindgen_start();
            return wasm;
        }

        async function __wbg_load(module, imports) {
            if (typeof Response === 'function' && module instanceof Response) {
                if (typeof WebAssembly.instantiateStreaming === 'function') {
                    try {
                        return await WebAssembly.instantiateStreaming(module, imports);
                    } catch (e) {
                        const validResponse = module.ok && expectedResponseType(module.type);

                        if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
                            console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                        } else { throw e; }
                    }
                }

                const bytes = await module.arrayBuffer();
                return await WebAssembly.instantiate(bytes, imports);
            } else {
                const instance = await WebAssembly.instantiate(module, imports);

                if (instance instanceof WebAssembly.Instance) {
                    return { instance, module };
                } else {
                    return instance;
                }
            }

            function expectedResponseType(type) {
                switch (type) {
                    case 'basic': case 'cors': case 'default': return true;
                }
                return false;
            }
        }

        function initSync(module) {
            if (wasm !== undefined) return wasm;


            if (module !== undefined) {
                if (Object.getPrototypeOf(module) === Object.prototype) {
                    ({ module } = module)
                } else {
                    console.warn('using deprecated parameters for `initSync()`; pass a single object instead')
                }
            }

            const imports = __wbg_get_imports();
            if (!(module instanceof WebAssembly.Module)) {
                module = new WebAssembly.Module(module);
            }
            const instance = new WebAssembly.Instance(module, imports);
            return __wbg_finalize_init(instance, module);
        }

        async function __wbg_init(module_or_path) {
            if (wasm !== undefined) return wasm;


            if (module_or_path !== undefined) {
                if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
                    ({ module_or_path } = module_or_path)
                } else {
                    console.warn('using deprecated parameters for the initialization function; pass a single object instead')
                }
            }

            if (module_or_path === undefined && script_src !== undefined) {
                module_or_path = script_src.replace(/\.js$/, "_bg.wasm");
            }
            const imports = __wbg_get_imports();

            if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
                module_or_path = fetch(module_or_path);
            }

            const { instance, module } = await __wbg_load(await module_or_path, imports);

            return __wbg_finalize_init(instance, module);
        }

        return Object.assign(__wbg_init, { initSync }, exports);
    })({ __proto__: null });

    // 2. ВАША BASE64 СТРОКА (из шага 2)
    const WASM_BASE64 = "AGFzbQEAAAABswEcYAJ/fwBgAn9/AX9gA39/fwF/YAF/AGADf39/AGAAAX9gBH9/f38Bf2AAAGAFf39/f38AYAFvAX9gAn9/AW9gAX8Bf2AGf39/f39/AGAFf39/f38Bf2AEf39/fwBgAAJ/f2AAAW9gAn9vAGABbwBgAm9vAW9gAn9/An9/YAZ/f39/f38Bf2AFf398f38AYAR/fH9/AGAFf399f38AYAR/fX9/AGAFf39+f38AYAR/fn9/AALmBhEMLi93YXNtX2JnLmpzGl9fd2JnX25ld184YTZmMjM4YTZlY2U4NmVhABAMLi93YXNtX2JnLmpzHF9fd2JnX3N0YWNrXzBlZDc1ZDY4NTc1YjBmM2MAEQwuL3dhc21fYmcuanMcX193YmdfZXJyb3JfNzUzNGI4ZTlhMzZmMWFiNAAADC4vd2FzbV9iZy5qcyhfX3diZ19pbnN0YW5jZW9mX1dpbmRvd19lZDQ5YjJkYjhkZjkwMzU5AAkMLi93YXNtX2JnLmpzG19fd2JnX3RpbWVfZmU3ZTQ3NTBhZjA1ZmE5NgAADC4vd2FzbV9iZy5qcx5fX3diZ190aW1lRW5kXzRiN2M0MzkzYzkyZjc1NWMAAAwuL3dhc21fYmcuanMaX193YmdfbG9nXzZiNWNhMmU2MTI0YjI4MDgAEgwuL3dhc21fYmcuanMbX193YmdfY2FsbF8zODllZmUyODQzNWE5Mzg4ABMMLi93YXNtX2JnLmpzIl9fd2JnX25ld19ub19hcmdzXzFjN2M4NDJmMDhkMDBlYmIACgwuL3dhc21fYmcuanMyX193Ymdfc3RhdGljX2FjY2Vzc29yX0dMT0JBTF9USElTX2U2MjhlODlhYjNiMWM5NWYABQwuL3dhc21fYmcuanMrX193Ymdfc3RhdGljX2FjY2Vzc29yX1NFTEZfYTYyMWQzZGZiYjYwZDBjZQAFDC4vd2FzbV9iZy5qcy1fX3diZ19zdGF0aWNfYWNjZXNzb3JfR0xPQkFMXzEyODM3MTY3YWQ5MzUxMTYABQwuL3dhc21fYmcuanMtX193Ymdfc3RhdGljX2FjY2Vzc29yX1dJTkRPV19mODcyN2YwY2Y4ODhlMGJkAAUMLi93YXNtX2JnLmpzJ19fd2JnX19fd2JpbmRnZW5fdGhyb3dfYmUyODlkNTAzNGVkMjcxYgAADC4vd2FzbV9iZy5qcy5fX3diZ19fX3diaW5kZ2VuX2lzX3VuZGVmaW5lZF85ZTRkOTI1MzRjNDJkNzc4AAkMLi93YXNtX2JnLmpzH19fd2JpbmRnZW5faW5pdF9leHRlcm5yZWZfdGFibGUABwwuL3dhc21fYmcuanMgX193YmluZGdlbl9jYXN0XzAwMDAwMDAwMDAwMDAwMDEACgNRUAsFAwIGAAABAAUAAQEBAAgMDAQABAQDCAICAgMBAAQBAQYGAxQVCA0WGBoDBw4CAwAAAAMDAwMEBAIBAQYDAAELBAICAgEBBwAAAQEAAAAHBAkCcAE2Nm8AgAEFAwEAEQYJAX8BQYCAwAALB7kBCgZtZW1vcnkCAAVncmVldAA1DWdyZWV0X2FuZF9sb2cAPRRfX3diaW5kZ2VuX2V4bl9zdG9yZQBOF19fZXh0ZXJucmVmX3RhYmxlX2FsbG9jABoVX193YmluZGdlbl9leHRlcm5yZWZzAQEPX193YmluZGdlbl9mcmVlAEkRX193YmluZGdlbl9tYWxsb2MAMBJfX3diaW5kZ2VuX3JlYWxsb2MAMxBfX3diaW5kZ2VuX3N0YXJ0AGAJOwEAQQELNUxfX19AKh1TVzghOTc6Oz43Nzg2PxJERUZHEF0tTEApHFRQLk9ZPDEfJF5CQUArHlVbXExLDAEGCoaTAVDJJQIJfwF+IwBBEGsiCCQAAkACQAJAAkACQCAAQfUBTwRAIABBzP97SwRAQQAhAAwGCyAAQQtqIgJBeHEhBUGYlsAAKAIAIglFDQRBHyEGQQAgBWshAyAAQfT//wdNBEAgBUEmIAJBCHZnIgBrdkEBcSAAQQF0a0E+aiEGCyAGQQJ0QfySwABqKAIAIgJFBEBBACEADAILIAVBGSAGQQF2a0EAIAZBH0cbdCEEQQAhAANAAkAgAigCBEF4cSIHIAVJDQAgByAFayIHIANPDQAgAiEBIAciAw0AQQAhAyABIQAMBAsgAigCFCIHIAAgByACIARBHXZBBHFqKAIQIgJHGyAAIAcbIQAgBEEBdCEEIAINAAsMAQsCQAJAAkACQAJAQZSWwAAoAgAiBEEQIABBC2pB+ANxIABBC0kbIgVBA3YiAHYiAUEDcQRAIAFBf3NBAXEgAGoiB0EDdCIBQYyUwABqIgAgAUGUlMAAaigCACICKAIIIgNGDQEgAyAANgIMIAAgAzYCCAwCCyAFQZyWwAAoAgBNDQggAQ0CQZiWwAAoAgAiAEUNCCAAaEECdEH8ksAAaigCACICKAIEQXhxIAVrIQMgAiEBA0ACQCABKAIQIgANACABKAIUIgANACACKAIYIQYCQAJAIAIgAigCDCIARgRAIAJBFEEQIAIoAhQiABtqKAIAIgENAUEAIQAMAgsgAigCCCIBIAA2AgwgACABNgIIDAELIAJBFGogAkEQaiAAGyEEA0AgBCEHIAEiAEEUaiAAQRBqIAAoAhQiARshBCAAQRRBECABG2ooAgAiAQ0ACyAHQQA2AgALIAZFDQYCQCACKAIcQQJ0QfySwABqIgEoAgAgAkcEQCACIAYoAhBHBEAgBiAANgIUIAANAgwJCyAGIAA2AhAgAA0BDAgLIAEgADYCACAARQ0GCyAAIAY2AhggAigCECIBBEAgACABNgIQIAEgADYCGAsgAigCFCIBRQ0GIAAgATYCFCABIAA2AhgMBgsgACgCBEF4cSAFayIBIAMgASADSSIBGyEDIAAgAiABGyECIAAhAQwACwALQZSWwAAgBEF+IAd3cTYCAAsgAkEIaiEAIAIgAUEDcjYCBCABIAJqIgEgASgCBEEBcjYCBAwHCwJAQQIgAHQiAkEAIAJrciABIAB0cWgiB0EDdCIBQYyUwABqIgIgAUGUlMAAaigCACIAKAIIIgNHBEAgAyACNgIMIAIgAzYCCAwBC0GUlsAAIARBfiAHd3E2AgALIAAgBUEDcjYCBCAAIAVqIgYgASAFayIHQQFyNgIEIAAgAWogBzYCAEGclsAAKAIAIgIEQEGklsAAKAIAIQECQEGUlsAAKAIAIgRBASACQQN2dCIDcUUEQEGUlsAAIAMgBHI2AgAgAkF4cUGMlMAAaiIDIQQMAQsgAkF4cSICQYyUwABqIQQgAkGUlMAAaigCACEDCyAEIAE2AgggAyABNgIMIAEgBDYCDCABIAM2AggLIABBCGohAEGklsAAIAY2AgBBnJbAACAHNgIADAYLQZiWwABBmJbAACgCAEF+IAIoAhx3cTYCAAsCQAJAIANBEE8EQCACIAVBA3I2AgQgAiAFaiIHIANBAXI2AgQgAyAHaiADNgIAQZyWwAAoAgAiAUUNAUGklsAAKAIAIQACQEGUlsAAKAIAIgRBASABQQN2dCIGcUUEQEGUlsAAIAQgBnI2AgAgAUF4cUGMlMAAaiIEIQEMAQsgAUF4cSIEQYyUwABqIQEgBEGUlMAAaigCACEECyABIAA2AgggBCAANgIMIAAgATYCDCAAIAQ2AggMAQsgAiADIAVqIgBBA3I2AgQgACACaiIAIAAoAgRBAXI2AgQMAQtBpJbAACAHNgIAQZyWwAAgAzYCAAsgAkEIaiIARQ0DDAQLIAAgAXJFBEBBACEBQQIgBnQiAEEAIABrciAJcSIARQ0DIABoQQJ0QfySwABqKAIAIQALIABFDQELA0AgAyAAKAIEQXhxIgIgBWsiBCADIAMgBEsiBBsgAiAFSSICGyEDIAEgACABIAQbIAIbIQEgACgCECICBH8gAgUgACgCFAsiAA0ACwsgAUUNACAFQZyWwAAoAgAiAE0gAyAAIAVrT3ENACABKAIYIQYCQAJAIAEgASgCDCIARgRAIAFBFEEQIAEoAhQiABtqKAIAIgINAUEAIQAMAgsgASgCCCICIAA2AgwgACACNgIIDAELIAFBFGogAUEQaiAAGyEEA0AgBCEHIAIiAEEUaiAAQRBqIAAoAhQiAhshBCAAQRRBECACG2ooAgAiAg0ACyAHQQA2AgALAkAgBkUNAAJAAkAgASgCHEECdEH8ksAAaiICKAIAIAFHBEAgASAGKAIQRwRAIAYgADYCFCAADQIMBAsgBiAANgIQIAANAQwDCyACIAA2AgAgAEUNAQsgACAGNgIYIAEoAhAiAgRAIAAgAjYCECACIAA2AhgLIAEoAhQiAkUNASAAIAI2AhQgAiAANgIYDAELQZiWwABBmJbAACgCAEF+IAEoAhx3cTYCAAsCQCADQRBPBEAgASAFQQNyNgIEIAEgBWoiACADQQFyNgIEIAAgA2ogAzYCACADQYACTwRAIAAgAxAbDAILAkBBlJbAACgCACICQQEgA0EDdnQiBHFFBEBBlJbAACACIARyNgIAIANB+AFxQYyUwABqIgMhAgwBCyADQfgBcSIEQYyUwABqIQIgBEGUlMAAaigCACEDCyACIAA2AgggAyAANgIMIAAgAjYCDCAAIAM2AggMAQsgASADIAVqIgBBA3I2AgQgACABaiIAIAAoAgRBAXI2AgQLIAFBCGoiAA0BCwJAAkACQAJAAkAgBUGclsAAKAIAIgFLBEAgBUGglsAAKAIAIgBPBEAgCEEEaiEAAn8gBUGvgARqQYCAfHEiAUEQdiABQf//A3FBAEdqIgFAACIEQX9GBEBBACEBQQAMAQsgAUEQdCICQRBrIAIgBEEQdCIBQQAgAmtGGwshAiAAQQA2AgggACACNgIEIAAgATYCACAIKAIEIgFFBEBBACEADAgLIAgoAgwhB0GslsAAIAgoAggiBEGslsAAKAIAaiIANgIAQbCWwAAgAEGwlsAAKAIAIgIgACACSxs2AgACQAJAQaiWwAAoAgAiAgRAQfyTwAAhAANAIAEgACgCACIDIAAoAgQiBmpGDQIgACgCCCIADQALDAILQbiWwAAoAgAiAEEAIAAgAU0bRQRAQbiWwAAgATYCAAtBvJbAAEH/HzYCAEGIlMAAIAc2AgBBgJTAACAENgIAQfyTwAAgATYCAEGYlMAAQYyUwAA2AgBBoJTAAEGUlMAANgIAQZSUwABBjJTAADYCAEGolMAAQZyUwAA2AgBBnJTAAEGUlMAANgIAQbCUwABBpJTAADYCAEGklMAAQZyUwAA2AgBBuJTAAEGslMAANgIAQayUwABBpJTAADYCAEHAlMAAQbSUwAA2AgBBtJTAAEGslMAANgIAQciUwABBvJTAADYCAEG8lMAAQbSUwAA2AgBB0JTAAEHElMAANgIAQcSUwABBvJTAADYCAEHYlMAAQcyUwAA2AgBBzJTAAEHElMAANgIAQdSUwABBzJTAADYCAEHglMAAQdSUwAA2AgBB3JTAAEHUlMAANgIAQeiUwABB3JTAADYCAEHklMAAQdyUwAA2AgBB8JTAAEHklMAANgIAQeyUwABB5JTAADYCAEH4lMAAQeyUwAA2AgBB9JTAAEHslMAANgIAQYCVwABB9JTAADYCAEH8lMAAQfSUwAA2AgBBiJXAAEH8lMAANgIAQYSVwABB/JTAADYCAEGQlcAAQYSVwAA2AgBBjJXAAEGElcAANgIAQZiVwABBjJXAADYCAEGglcAAQZSVwAA2AgBBlJXAAEGMlcAANgIAQaiVwABBnJXAADYCAEGclcAAQZSVwAA2AgBBsJXAAEGklcAANgIAQaSVwABBnJXAADYCAEG4lcAAQayVwAA2AgBBrJXAAEGklcAANgIAQcCVwABBtJXAADYCAEG0lcAAQayVwAA2AgBByJXAAEG8lcAANgIAQbyVwABBtJXAADYCAEHQlcAAQcSVwAA2AgBBxJXAAEG8lcAANgIAQdiVwABBzJXAADYCAEHMlcAAQcSVwAA2AgBB4JXAAEHUlcAANgIAQdSVwABBzJXAADYCAEHolcAAQdyVwAA2AgBB3JXAAEHUlcAANgIAQfCVwABB5JXAADYCAEHklcAAQdyVwAA2AgBB+JXAAEHslcAANgIAQeyVwABB5JXAADYCAEGAlsAAQfSVwAA2AgBB9JXAAEHslcAANgIAQYiWwABB/JXAADYCAEH8lcAAQfSVwAA2AgBBkJbAAEGElsAANgIAQYSWwABB/JXAADYCAEGolsAAIAFBD2pBeHEiAEEIayICNgIAQYyWwABBhJbAADYCAEGglsAAIARBKGsiBCABIABrakEIaiIANgIAIAIgAEEBcjYCBCABIARqQSg2AgRBtJbAAEGAgIABNgIADAgLIAIgA0kgASACTXINACAAKAIMIgNBAXENACADQQF2IAdGDQMLQbiWwABBuJbAACgCACIAIAEgACABSRs2AgAgASAEaiEDQfyTwAAhAAJAAkADQCADIAAoAgAiBkcEQCAAKAIIIgANAQwCCwsgACgCDCIDQQFxDQAgA0EBdiAHRg0BC0H8k8AAIQADQAJAIAIgACgCACIDTwRAIAIgAyAAKAIEaiIGSQ0BCyAAKAIIIQAMAQsLQaiWwAAgAUEPakF4cSIAQQhrIgM2AgBBoJbAACAEQShrIgkgASAAa2pBCGoiADYCACADIABBAXI2AgQgASAJakEoNgIEQbSWwABBgICAATYCACACIAZBIGtBeHFBCGsiACAAIAJBEGpJGyIDQRs2AgRB/JPAACkCACEKIANBEGpBhJTAACkCADcCACADQQhqIgAgCjcCAEGIlMAAIAc2AgBBgJTAACAENgIAQfyTwAAgATYCAEGElMAAIAA2AgAgA0EcaiEAA0AgAEEHNgIAIABBBGoiACAGSQ0ACyACIANGDQcgAyADKAIEQX5xNgIEIAIgAyACayIAQQFyNgIEIAMgADYCACAAQYACTwRAIAIgABAbDAgLAkBBlJbAACgCACIBQQEgAEEDdnQiBHFFBEBBlJbAACABIARyNgIAIABB+AFxQYyUwABqIgAhAQwBCyAAQfgBcSIAQYyUwABqIQEgAEGUlMAAaigCACEACyABIAI2AgggACACNgIMIAIgATYCDCACIAA2AggMBwsgACABNgIAIAAgACgCBCAEajYCBCABQQ9qQXhxQQhrIgQgBUEDcjYCBCAGQQ9qQXhxQQhrIgMgBCAFaiIAayEFIANBqJbAACgCAEYNAyADQaSWwAAoAgBGDQQgAygCBCICQQNxQQFGBEAgAyACQXhxIgEQGSABIAVqIQUgASADaiIDKAIEIQILIAMgAkF+cTYCBCAAIAVBAXI2AgQgACAFaiAFNgIAIAVBgAJPBEAgACAFEBsMBgsCQEGUlsAAKAIAIgFBASAFQQN2dCICcUUEQEGUlsAAIAEgAnI2AgAgBUH4AXFBjJTAAGoiBSEDDAELIAVB+AFxIgFBjJTAAGohAyABQZSUwABqKAIAIQULIAMgADYCCCAFIAA2AgwgACADNgIMIAAgBTYCCAwFC0GglsAAIAAgBWsiATYCAEGolsAAQaiWwAAoAgAiACAFaiICNgIAIAIgAUEBcjYCBCAAIAVBA3I2AgQgAEEIaiEADAYLQaSWwAAoAgAhAAJAIAEgBWsiAkEPTQRAQaSWwABBADYCAEGclsAAQQA2AgAgACABQQNyNgIEIAAgAWoiASABKAIEQQFyNgIEDAELQZyWwAAgAjYCAEGklsAAIAAgBWoiBDYCACAEIAJBAXI2AgQgACABaiACNgIAIAAgBUEDcjYCBAsgAEEIaiEADAULIAAgBCAGajYCBEGolsAAQaiWwAAoAgAiAEEPakF4cSIBQQhrIgI2AgBBoJbAAEGglsAAKAIAIARqIgQgACABa2pBCGoiATYCACACIAFBAXI2AgQgACAEakEoNgIEQbSWwABBgICAATYCAAwDC0GolsAAIAA2AgBBoJbAAEGglsAAKAIAIAVqIgE2AgAgACABQQFyNgIEDAELQaSWwAAgADYCAEGclsAAQZyWwAAoAgAgBWoiATYCACAAIAFBAXI2AgQgACABaiABNgIACyAEQQhqIQAMAQtBACEAQaCWwAAoAgAiASAFTQ0AQaCWwAAgASAFayIBNgIAQaiWwABBqJbAACgCACIAIAVqIgI2AgAgAiABQQFyNgIEIAAgBUEDcjYCBCAAQQhqIQALIAhBEGokACAAC/4FAgV/AW8jAEEwayICJAACQAJAAkBBkJLAACgCACIBQQJHDQBBmJLAACgCACEAQZiSwABBADYCACAARQ0BIAJBIGogABEDACACKAIkIQMgAigCICEAQZCSwAAoAgAiAUECRgRAQZSSwAAgAzYCAEGQksAAIAA2AgAgACEBDAELIABBAkcNAgsCQAJAIAICf0GUksAAIAFBAXENABoCQEGoksAAKAIAIgFBAkcNAEGwksAAKAIAIQBBsJLAAEEANgIAIABFDQQgAkEYaiAAEQMAIAIoAhwhAyACKAIYIQBBqJLAACgCACIBQQJGBEBBrJLAACADNgIAQaiSwAAgADYCACAAIQEMAQsgAEECRw0FC0GsksAAIAFBAXENABoCQEGEksAAKAIAIgFBAkcNAEGMksAAKAIAIQBBjJLAAEEANgIAIABFDQQgAkEQaiAAEQMAIAIoAhQhAyACKAIQIQBBhJLAACgCACIBQQJGBEBBiJLAACADNgIAQYSSwAAgADYCACAAIQEMAQsgAEECRw0FC0GIksAAIAFBAXENABoCQEGcksAAKAIAIgFBAkcNAEGkksAAKAIAIQBBpJLAAEEANgIAIABFDQQgAkEIaiAAEQMAIAIoAgwhAyACKAIIIQBBnJLAACgCACIBQQJGBEBBoJLAACADNgIAQZySwAAgADYCACAAIQEMAQsgAEECRw0FCyABQQFxRQ0BQaCSwAALKAIAEFEiATYCLCACQSxqKAIAJQEQDkUNASABQYQBSQ0AIAEQJwtBjYrAAEELEAghBRAaIgAgBSYBIAAlAUGAASUBEAchBRAaIgEgBSYBQdySwAAoAgAhBEHYksAAKAIAIQNB2JLAAEIANwIAIANBAUcgBEGDAU1yRQRAIAQQJwsgAEGEAU8EQCAAECcLQYABIAEgA0EBRhshAQsgAkEwaiQAIAEPC0HqisAAQdUAQZSLwAAQLwALIABFIABBAkZyIANBhAFJckUEQCADECcLQZiKwABBHUGoisAAEC8AC5QGAQV/IABBCGsiASAAQQRrKAIAIgNBeHEiAGohAgJAAkAgA0EBcQ0AIANBAnFFDQEgASgCACIDIABqIQAgASADayIBQaSWwAAoAgBGBEAgAigCBEEDcUEDRw0BQZyWwAAgADYCACACIAIoAgRBfnE2AgQgASAAQQFyNgIEIAIgADYCAA8LIAEgAxAZCwJAAkACQAJAAkAgAigCBCIDQQJxRQRAIAJBqJbAACgCAEYNAiACQaSWwAAoAgBGDQMgAiADQXhxIgIQGSABIAAgAmoiAEEBcjYCBCAAIAFqIAA2AgAgAUGklsAAKAIARw0BQZyWwAAgADYCAA8LIAIgA0F+cTYCBCABIABBAXI2AgQgACABaiAANgIACyAAQYACSQ0CIAEgABAbQQAhAUG8lsAAQbyWwAAoAgBBAWsiADYCACAADQRBhJTAACgCACIABEADQCABQQFqIQEgACgCCCIADQALC0G8lsAAQf8fIAEgAUH/H00bNgIADwtBqJbAACABNgIAQaCWwABBoJbAACgCACAAaiIANgIAIAEgAEEBcjYCBEGklsAAKAIAIAFGBEBBnJbAAEEANgIAQaSWwABBADYCAAsgAEG0lsAAKAIAIgNNDQNBqJbAACgCACICRQ0DQQAhAEGglsAAKAIAIgRBKUkNAkH8k8AAIQEDQCACIAEoAgAiBU8EQCACIAUgASgCBGpJDQQLIAEoAgghAQwACwALQaSWwAAgATYCAEGclsAAQZyWwAAoAgAgAGoiADYCACABIABBAXI2AgQgACABaiAANgIADwsCQEGUlsAAKAIAIgJBASAAQQN2dCIDcUUEQEGUlsAAIAIgA3I2AgAgAEH4AXFBjJTAAGoiACECDAELIABB+AFxIgBBjJTAAGohAiAAQZSUwABqKAIAIQALIAIgATYCCCAAIAE2AgwgASACNgIMIAEgADYCCA8LQYSUwAAoAgAiAQRAA0AgAEEBaiEAIAEoAggiAQ0ACwtBvJbAAEH/HyAAIABB/x9NGzYCACADIARPDQBBtJbAAEF/NgIACwuICwELfwJAAkAgACgCCCINQYCAgMABcUUNAAJAAkACQAJAIA1BgICAgAFxBEAgAC8BDiIFDQFBACECDAILIAJBEE8EQAJ/AkACQCACIAFBA2pBfHEiBCABayIDSQ0AIAIgA2siC0EESQ0AIAEgBEcEQCABIARrIgRBfE0EQANAIAUgASAJaiIHLAAAQb9/SmogB0EBaiwAAEG/f0pqIAdBAmosAABBv39KaiAHQQNqLAAAQb9/SmohBSAJQQRqIgkNAAsLIAEgCWohCANAIAUgCCwAAEG/f0pqIQUgCEEBaiEIIARBAWoiBA0ACwsgASADaiEEAkAgC0EDcSIHRQ0AIAQgC0H8////B3FqIgMsAABBv39KIQogB0EBRg0AIAogAywAAUG/f0pqIQogB0ECRg0AIAogAywAAkG/f0pqIQoLIAtBAnYhDCAFIApqIQkDQCAEIQMgDEUNAkHAASAMIAxBwAFPGyIGQQNxIQoCQCAGQQJ0IgtB8AdxIgRFBEBBACEIDAELIAMgBGohB0EAIQggAyEFA0AgCCAFKAIAIgRBf3NBB3YgBEEGdnJBgYKECHFqIAVBBGooAgAiBEF/c0EHdiAEQQZ2ckGBgoQIcWogBUEIaigCACIEQX9zQQd2IARBBnZyQYGChAhxaiAFQQxqKAIAIgRBf3NBB3YgBEEGdnJBgYKECHFqIQggBUEQaiIFIAdHDQALCyAMIAZrIQwgAyALaiEEIAhBCHZB/4H8B3EgCEH/gfwHcWpBgYAEbEEQdiAJaiEJIApFDQALAn8gAyAGQfwBcUECdGoiBSgCACIDQX9zQQd2IANBBnZyQYGChAhxIgQgCkEBRg0AGiAEIAUoAgQiA0F/c0EHdiADQQZ2ckGBgoQIcWoiAyAKQQJGDQAaIAMgBSgCCCIDQX9zQQd2IANBBnZyQYGChAhxagsiA0EIdkH/gRxxIANB/4H8B3FqQYGABGxBEHYgCWohCQwBC0EAIAJFDQEaIAJBA3EhBCACQQRPBEAgAkF8cSEDA0AgCSABIAhqIgUsAABBv39KaiAFQQFqLAAAQb9/SmogBUECaiwAAEG/f0pqIAVBA2osAABBv39KaiEJIAMgCEEEaiIIRw0ACwsgBEUNACABIAhqIQUDQCAJIAUsAABBv39KaiEJIAVBAWohBSAEQQFrIgQNAAsLIAkLIQYMBAsgAkUNAyACQQNxIQcgAkEETwRAIAJBDHEhAwNAIAYgASAEaiIFLAAAQb9/SmogBUEBaiwAAEG/f0pqIAVBAmosAABBv39KaiAFQQNqLAAAQb9/SmohBiADIARBBGoiBEcNAAsLIAdFDQMgASAEaiEDA0AgBiADLAAAQb9/SmohBiADQQFqIQMgB0EBayIHDQALDAMLIAEgAmohC0EAIQIgASEDIAUhBANAIAMiByALRg0CIAICfyADQQFqIAMsAAAiAkEATg0AGiADQQJqIAJBYEkNABogA0EDaiACQXBJDQAaIANBBGoLIgMgB2tqIQIgBEEBayIEDQALC0EAIQQLIAUgBGshBgsgBiAALwEMIgNPDQAgAyAGayEFQQAhBkEAIQQCQAJAAkAgDUEddkEDcUEBaw4CAAECCyAFIQQMAQsgBUH+/wNxQQF2IQQLIA1B////AHEhByAAKAIEIQogACgCACELA0AgBkH//wNxIARB//8DcUkEQEEBIQMgBkEBaiEGIAsgByAKKAIQEQEARQ0BDAMLC0EBIQMgCyABIAIgCigCDBECAA0BQQAhBiAFIARrQf//A3EhAQNAIAZB//8DcSIAIAFJIQMgACABTw0CIAZBAWohBiALIAcgCigCEBEBAEUNAAsMAQsgACgCACABIAIgACgCBCgCDBECACEDCyADC/sDAQh/IwBBEGsiBiQAAn8CQCADQQFxRQRAIAItAAAiBQ0BQQAMAgsgACACIANBAXYgASgCDBECAAwBCyABKAIMIQoDQCACQQFqIQQCQAJAAkACQCAFwEEASARAIAVB/wFxIghBgAFGDQEgCEHAAUcNAyAGIAE2AgQgBiAANgIAIAZCoICAgAY3AgggAyAHQQN0aiICKAIAIAYgAigCBBEBAEUNAkEBDAYLIAAgBCAFQf8BcSICIAoRAgBFBEAgAiAEaiECDAQLQQEMBQsgACACQQNqIgQgAi8AASICIAoRAgBFBEAgAiAEaiECDAMLQQEMBAsgB0EBaiEHIAQhAgwBC0GggICABiELIAVBAXEEQCACKAABIQsgAkEFaiEEC0EAIQgCfyAFQQJxRQRAQQAhCSAEDAELIAQvAAAhCSAEQQJqCyECIAVBBHEEfyACLwAAIQggAkECagUgAgshBCAFQQhxBH8gBC8AACEHIARBAmoFIAQLIQIgBUEQcQRAIAMgCUEDdGovAQQhCQsgBiAFQSBxBH8gAyAIQQN0ai8BBAUgCAs7AQ4gBiAJOwEMIAYgCzYCCCAGIAE2AgQgBiAANgIAQQEgAyAHQQN0aiIEKAIAIAYgBCgCBBEBAA0CGiAHQQFqIQcLIAItAAAiBQ0AC0EACyAGQRBqJAALjwQBAn8gACABaiECAkACQCAAKAIEIgNBAXENACADQQJxRQ0BIAAoAgAiAyABaiEBIAAgA2siAEGklsAAKAIARgRAIAIoAgRBA3FBA0cNAUGclsAAIAE2AgAgAiACKAIEQX5xNgIEIAAgAUEBcjYCBCACIAE2AgAMAgsgACADEBkLAkACQAJAIAIoAgQiA0ECcUUEQCACQaiWwAAoAgBGDQIgAkGklsAAKAIARg0DIAIgA0F4cSICEBkgACABIAJqIgFBAXI2AgQgACABaiABNgIAIABBpJbAACgCAEcNAUGclsAAIAE2AgAPCyACIANBfnE2AgQgACABQQFyNgIEIAAgAWogATYCAAsgAUGAAk8EQCAAIAEQGw8LAkBBlJbAACgCACICQQEgAUEDdnQiA3FFBEBBlJbAACACIANyNgIAIAFB+AFxQYyUwABqIgEhAgwBCyABQfgBcSIBQYyUwABqIQIgAUGUlMAAaigCACEBCyACIAA2AgggASAANgIMIAAgAjYCDCAAIAE2AggPC0GolsAAIAA2AgBBoJbAAEGglsAAKAIAIAFqIgE2AgAgACABQQFyNgIEIABBpJbAACgCAEcNAUGclsAAQQA2AgBBpJbAAEEANgIADwtBpJbAACAANgIAQZyWwABBnJbAACgCACABaiIBNgIAIAAgAUEBcjYCBCAAIAFqIAE2AgALC48DAQZ/IwBBEGsiBCQAAkACQAJAAkACQAJAIAFBAXEEQCABQQF2IQIMAQtBjojAAC0AACICRQ0BQY6IwAAhAwNAIANBAWohAwJAIALAQQBIBEAgAkH/AXFBgAFGBEAgBSADLwAAIgJqIQUgAiADakECaiEDDAILIAMgAkEDcUEYdyIHQQV0QYCAgIAEcSAHQYCAgIACcSAHQYCAgAhxQQd0cnJBHXZqIAJBAXZBAnFqIAJBAnZBAnFqIQMgBUUgBnIhBgwBCyADIAJB/wFxIgJqIQMgAiAFaiEFCyADLQAAIgINAAtBACECIAYgBUEQSXENAEEAIQYgBUEBdCICQQBIDQQLIAINAQtBASEDQQAhAgwBC0EBIQYgAkEBEFYiA0UNAQsgBEEANgIIIAQgAzYCBCAEIAI2AgAgBEHMjsAAQY6IwAAgARAVRQ0BQfSOwABB1gAgBEEPakHkjsAAQcyPwAAQKAALIAYgAhBDAAsgACAEKQIANwIAIABBCGogBEEIaigCADYCACAEQRBqJAAL5wIBBX8CQCABQc3/e0EQIAAgAEEQTRsiAGtPDQAgAEEQIAFBC2pBeHEgAUELSRsiBGpBDGoQESICRQ0AIAJBCGshAQJAIABBAWsiAyACcUUEQCABIQAMAQsgAkEEayIFKAIAIgZBeHEgAiADakEAIABrcUEIayICIABBACACIAFrQRBNG2oiACABayICayEDIAZBA3EEQCAAIAMgACgCBEEBcXJBAnI2AgQgACADaiIDIAMoAgRBAXI2AgQgBSACIAUoAgBBAXFyQQJyNgIAIAEgAmoiAyADKAIEQQFyNgIEIAEgAhAWDAELIAEoAgAhASAAIAM2AgQgACABIAJqNgIACwJAIAAoAgQiAUEDcUUNACABQXhxIgIgBEEQak0NACAAIAQgAUEBcXJBAnI2AgQgACAEaiIBIAIgBGsiBEEDcjYCBCAAIAJqIgIgAigCBEEBcjYCBCABIAQQFgsgAEEIaiEDCyADC4IDAQR/IAAoAgwhAgJAAkACQCABQYACTwRAIAAoAhghAwJAAkAgACACRgRAIABBFEEQIAAoAhQiAhtqKAIAIgENAUEAIQIMAgsgACgCCCIBIAI2AgwgAiABNgIIDAELIABBFGogAEEQaiACGyEEA0AgBCEFIAEiAkEUaiACQRBqIAIoAhQiARshBCACQRRBECABG2ooAgAiAQ0ACyAFQQA2AgALIANFDQICQCAAKAIcQQJ0QfySwABqIgEoAgAgAEcEQCADKAIQIABGDQEgAyACNgIUIAINAwwECyABIAI2AgAgAkUNBAwCCyADIAI2AhAgAg0BDAILIAAoAggiACACRwRAIAAgAjYCDCACIAA2AggPC0GUlsAAQZSWwAAoAgBBfiABQQN2d3E2AgAPCyACIAM2AhggACgCECIBBEAgAiABNgIQIAEgAjYCGAsgACgCFCIARQ0AIAIgADYCFCAAIAI2AhgPCw8LQZiWwABBmJbAACgCAEF+IAAoAhx3cTYCAAvyAgEFfyMAQRBrIgMkAAJAQbSSwAAoAgBFBEBBtJLAAEF/NgIAQcSSwAAoAgAiAEHAksAAKAIAIgFGBEACfyAAIABBuJLAACgCACICRw0AGtBvQYABIAAgAEGAAU0bIgT8DwEiAkF/Rg0DAkBByJLAACgCACIBRQRAQciSwAAgAjYCAAwBCyAAIAFqIAJHDQQLQbiSwAAoAgAiASAAayAETwRAIAEhAiAADAELIANBBGogAUG8ksAAKAIAIAAgBGoiAkEEQQQQIiADKAIEQQFGDQNBvJLAACADKAIINgIAQbiSwAAgAjYCAEHAksAAKAIACyIBIAJPDQJBvJLAACgCACABQQJ0aiAAQQFqNgIAQcCSwAAgAUEBaiIBNgIACyAAIAFPDQFBxJLAAEG8ksAAKAIAIABBAnRqKAIANgIAQbSSwABBtJLAACgCAEEBajYCAEHIksAAKAIAIQEgA0EQaiQAIAAgAWoPC0Gki8AAEDQLAAvEAgEEfyAAQgA3AhAgAAJ/QQAgAUGAAkkNABpBHyABQf///wdLDQAaIAFBJiABQQh2ZyIDa3ZBAXEgA0EBdGtBPmoLIgI2AhwgAkECdEH8ksAAaiEEQQEgAnQiA0GYlsAAKAIAcUUEQCAEIAA2AgAgACAENgIYIAAgADYCDCAAIAA2AghBmJbAAEGYlsAAKAIAIANyNgIADwsCQAJAIAEgBCgCACIDKAIEQXhxRgRAIAMhAgwBCyABQRkgAkEBdmtBACACQR9HG3QhBQNAIAMgBUEddkEEcWoiBCgCECICRQ0CIAVBAXQhBSACIQMgAigCBEF4cSABRw0ACwsgAigCCCIBIAA2AgwgAiAANgIIIABBADYCGCAAIAI2AgwgACABNgIIDwsgBEEQaiAANgIAIAAgAzYCGCAAIAA2AgwgACAANgIIC4gCAQZ/IAAoAggiBCECAn9BASABQYABSQ0AGkECIAFBgBBJDQAaQQNBBCABQYCABEkbCyIGIAAoAgAgBGtLBH8gACAEIAYQIyAAKAIIBSACCyAAKAIEaiECAkAgAUGAAU8EQCABQT9xQYB/ciEFIAFBBnYhAyABQYAQSQRAIAIgBToAASACIANBwAFyOgAADAILIAFBDHYhByADQT9xQYB/ciEDIAFB//8DTQRAIAIgBToAAiACIAM6AAEgAiAHQeABcjoAAAwCCyACIAU6AAMgAiADOgACIAIgB0E/cUGAf3I6AAEgAiABQRJ2QXByOgAADAELIAIgAToAAAsgACAEIAZqNgIIQQALiAIBBn8gACgCCCIEIQICf0EBIAFBgAFJDQAaQQIgAUGAEEkNABpBA0EEIAFBgIAESRsLIgYgACgCACAEa0sEfyAAIAQgBhAlIAAoAggFIAILIAAoAgRqIQICQCABQYABTwRAIAFBP3FBgH9yIQUgAUEGdiEDIAFBgBBJBEAgAiAFOgABIAIgA0HAAXI6AAAMAgsgAUEMdiEHIANBP3FBgH9yIQMgAUH//wNNBEAgAiAFOgACIAIgAzoAASACIAdB4AFyOgAADAILIAIgBToAAyACIAM6AAIgAiAHQT9xQYB/cjoAASACIAFBEnZBcHI6AAAMAQsgAiABOgAACyAAIAQgBmo2AghBAAuIAgEGfyAAKAIIIgQhAgJ/QQEgAUGAAUkNABpBAiABQYAQSQ0AGkEDQQQgAUGAgARJGwsiBiAAKAIAIARrSwR/IAAgBCAGECYgACgCCAUgAgsgACgCBGohAgJAIAFBgAFPBEAgAUE/cUGAf3IhBSABQQZ2IQMgAUGAEEkEQCACIAU6AAEgAiADQcABcjoAAAwCCyABQQx2IQcgA0E/cUGAf3IhAyABQf//A00EQCACIAU6AAIgAiADOgABIAIgB0HgAXI6AAAMAgsgAiAFOgADIAIgAzoAAiACIAdBP3FBgH9yOgABIAIgAUESdkFwcjoAAAwBCyACIAE6AAALIAAgBCAGajYCCEEAC/oBAgN/AX4jAEEwayICJAAgASgCAEGAgICAeEYEQCABKAIMIQMgAkEsaiIEQQA2AgAgAkKAgICAEDcCJCACQSRqQcSLwAAgAygCACIDKAIAIAMoAgQQFRogAkEgaiAEKAIAIgM2AgAgAiACKQIkIgU3AxggAUEIaiADNgIAIAEgBTcCAAsgASkCACEFIAFCgICAgBA3AgAgAkEQaiIDIAFBCGoiASgCADYCACABQQA2AgAgAiAFNwMIQQxBBBBWIgFFBEBBBEEMEFoACyABIAIpAwg3AgAgAUEIaiADKAIANgIAIABBmI7AADYCBCAAIAE2AgAgAkEwaiQAC5QCAQJ/IwBBIGsiBSQAQfiSwABB+JLAACgCACIGQQFqNgIAAkACf0EAIAZBAEgNABpBAUHkksAALQAADQAaQeSSwABBAToAAEHgksAAQeCSwAAoAgBBAWo2AgBBAgtB/wFxIgZBAkcEQCAGQQFxRQ0BIAVBCGogACABKAIYEQAADAELQeySwAAoAgAiBkEASA0AQeySwAAgBkEBajYCAEHwksAAKAIABEAgBSAAIAEoAhQRAAAgBSAEOgAdIAUgAzoAHCAFIAI2AhggBSAFKQMANwIQQfCSwAAoAgAgBUEQakH0ksAAKAIAKAIUEQAAC0HsksAAQeySwAAoAgBBAWs2AgBB5JLAAEEAOgAAIANFDQAACwALngEBAX8jAEEQayIGJAACQCABBEAgBkEEaiABIAMgBCAFIAIoAhARCAACQCAGKAIEIgIgBigCDCIBTQRAIAYoAgghBQwBCyACQQJ0IQIgBigCCCEDIAFFBEBBBCEFIAMgAkEEEFIMAQsgAyACQQQgAUECdCICEE0iBUUNAgsgACABNgIEIAAgBTYCACAGQRBqJAAPCxBYAAtBBCACEEMAC5wBAgJ/AX5BASEHQQQhBgJAIAWtIAOtfiIIQiCIUEUEQEEAIQMMAQsgCKciA0GAgICAeCAEa0sEQEEAIQMMAQsCQAJAAn8gAQRAIAIgASAFbCAEIAMQTQwBCyADRQRAIAQhBgwCCyADIAQQVgsiBg0AIAAgBDYCBAwBCyAAIAY2AgRBACEHC0EIIQYLIAAgBmogAzYCACAAIAc2AgALhwEBAX8jAEEQayIDJAAgAiABIAJqIgFLBEBBAEEAEEMACyADQQRqIAAoAgAiAiAAKAIEQQggASACQQF0IgIgASACSxsiASABQQhNGyIBQQFBARAiIAMoAgRBAUYEQCADKAIIIAMoAgwQQwALIAMoAgghAiAAIAE2AgAgACACNgIEIANBEGokAAucAQIDfwF+IwBBIGsiAiQAIAEoAgBBgICAgHhGBEAgASgCDCEDIAJBHGoiBEEANgIAIAJCgICAgBA3AhQgAkEUakHEi8AAIAMoAgAiAygCACADKAIEEBUaIAJBEGogBCgCACIDNgIAIAIgAikCFCIFNwMIIAFBCGogAzYCACABIAU3AgALIABBmI7AADYCBCAAIAE2AgAgAkEgaiQAC+wBAQR/IwBBEGsiAyQAIAIgASACaiIESwRAQQBBABBDAAsgA0EEaiEBIAAoAgAiAiEFIAAoAgQhBgJAQQggBCACQQF0IgIgAiAESRsiAiACQQhNGyICQQBOBEACfyAFBEAgBiAFQQEgAhBNDAELIAJBARBWCyIERQRAIAEgAjYCCCABQQE2AgQgAUEBNgIADAILIAEgAjYCCCABIAQ2AgQgAUEANgIADAELIAFBADYCBCABQQE2AgALIAMoAgRBAUYEQCADKAIIIAMoAgwQQwALIAMoAgghASAAIAI2AgAgACABNgIEIANBEGokAAvxAQEEfyMAQRBrIgMkACACIAEgAmoiAUsEQEEAQQAQQwALIANBBGohBCAAKAIEIQYCf0EIIAEgACgCACICQQF0IgUgASAFSxsiASABQQhNGyIFIgFBAEgEQEEBIQJBACEBQQQMAQsCfwJAAn8gAgRAIAYgAkEBIAEQTQwBCyABRQRAQQEhAgwCCyABQQEQVgsiAg0AIARBATYCBEEBDAELIAQgAjYCBEEACyECQQgLIARqIAE2AgAgBCACNgIAIAMoAgRBAUYEQCADKAIIIAMoAgwQQwALIAMoAgghASAAIAU2AgAgACABNgIEIANBEGokAAuOAQEBfwJAAkAgAEGEAU8EQCAA0G8mAUG0ksAAKAIADQJBtJLAAEF/NgIAIABByJLAACgCACIBSQ0BIAAgAWsiAEHAksAAKAIATw0BQbySwAAoAgAgAEECdGpBxJLAACgCADYCAEHEksAAIAA2AgBBtJLAAEG0ksAAKAIAQQFqNgIACw8LAAtBtIvAABA0AAtbAQF/IwBBIGsiBSQAIAUgATYCBCAFIAA2AgAgBSADNgIMIAUgAjYCCCAFIAVBCGqtQoCAgIDQBoQ3AxggBSAFrUKAgICAwAaENwMQQaGBwAAgBUEQaiAEEC8AC1QBAX8CQAJAIAAoAgAgACgCCCIDayACSQRAIAAgAyACECMgACgCCCEDDAELIAJFDQELIAJFDQAgACgCBCADaiABIAL8CgAACyAAIAIgA2o2AghBAAtUAQF/AkACQCAAKAIAIAAoAggiA2sgAkkEQCAAIAMgAhAlIAAoAgghAwwBCyACRQ0BCyACRQ0AIAAoAgQgA2ogASAC/AoAAAsgACACIANqNgIIQQALVAEBfwJAAkAgACgCACAAKAIIIgNrIAJJBEAgACADIAIQJiAAKAIIIQMMAQsgAkUNAQsgAkUNACAAKAIEIANqIAEgAvwKAAALIAAgAiADajYCCEEAC1MBAX8jAEEgayIBJAAgAUEKNgIMIAEgADYCCCABIAFBCGqtQoCAgIDQA4Q3AxggASABQQxqrUKAgICA0AOENwMQQeqAwAAgAUEQakHkj8AAEC8AC9sHAgx/AX4jAEEQayINJAACfyABIQUgDUEGaiEGQQohAiAAKAIAIgkiAEHoB08EQCAGQQRrIQQgACEBAkACQANAIAEgAUGQzgBuIgBBkM4AbGsiC0H//wNxQeQAbiEIAkAgA0EKaiIKQQRrQQpJBEAgBEEKaiIHIAhBAXQiDC0An5BAOgAAIApBA2siAkEKSQ0BIAIQLAALIApBBGsQLAALIAdBAWogDEGgkMAAai0AADoAACAKQQJrQQpJBEAgB0ECaiALIAhB5ABsa0EBdEH+/wdxIgItAJ+QQDoAACAKQQFrQQpPDQIgB0EDaiACQaCQwABqLQAAOgAAIARBBGshBCADQQRrIQMgAUH/rOIESyAAIQFFDQMMAQsLIApBAmsQLAALIApBAWsQLAALIANBCmohAgsCQCAAQQlNBEAgACEDIAIhAQwBCyAAQf//A3FB5ABuIQMCQCACQQJrIgFBCkkEQCABIAZqIAAgA0HkAGxrQf//A3FBAXQiAC0An5BAOgAAIAJBAWsiAkEKTw0BIAIgBmogAEGgkMAAai0AADoAAAwCCyABECwACyACECwAC0EAIAkgAxtFBEAgAUEBayIBQQpPBEAgARAsAAsgASAGaiADQQF0LQCgkEA6AAALIAEgBmohC0EKIAFrIQhBACEEQQFBK0GAgMQAIAUoAggiAkGAgIABcSIAGyEMQQAgAkGAgIAEcRshBgJAIABBFXYgCGoiAyAFLwEMIgBJBEACQAJAIAJBgICACHFFBEAgACADayEAQQAhAQJAAkACQCACQR12QQNxQQFrDgMAAQACCyAAIQEMAQsgAEH+/wNxQQF2IQELIAJB////AHEhAiAFKAIEIQkgBSgCACEDA0AgBEH//wNxIAFB//8DcU8NAkEBIQcgBEEBaiEEIAMgAiAJKAIQEQEARQ0ACwwECyAFIAUpAggiDqdBgICA/3lxQbCAgIACcjYCCEEBIQcgBSgCACICIAUoAgQiASAMIAYQMg0DIAAgA2tB//8DcSEAA0AgBEH//wNxIABPDQIgBEEBaiEEIAJBMCABKAIQEQEARQ0ACwwDC0EBIQcgAyAJIAwgBhAyDQIgAyALIAggCSgCDBECAA0CQQAhBCAAIAFrQf//A3EhAQNAIARB//8DcSIAIAFJIQcgACABTw0DIARBAWohBCADIAIgCSgCEBEBAEUNAAsMAgsgAiALIAggASgCDBECAA0BIAUgDjcCCEEADAILQQEhByAFKAIAIgEgBSgCBCIAIAwgBhAyDQAgASALIAggACgCDBECACEHCyAHCyANQRBqJAALRAECfyABKAIEIQIgASgCACEDQQhBBBBWIgFFBEBBBEEIEFoACyABIAI2AgQgASADNgIAIABB+I3AADYCBCAAIAE2AgAL3gECAX8BfiMAQSBrIgMkACADIAE2AhAgAyAANgIMIANBATsBHCADIAI2AhggAyADQQxqNgIUIwBBEGsiASQAIANBFGoiACkCACEEIAEgADYCDCABIAQ3AgQjAEEQayIAJAAgAUEEaiIBKAIAIgIoAgQiA0EBcQRAIAIoAgAhAiAAIANBAXY2AgQgACACNgIAIABB3IvAACABKAIEIAEoAggiAC0ACCAALQAJECAACyAAQYCAgIB4NgIAIAAgATYCDCAAQfiLwAAgASgCBCABKAIIIgAtAAggAC0ACRAgAAsuAAJAIAFpQQFHIABBgICAgHggAWtLcg0AIAAEQCAAIAEQViIBRQ0BCyABDwsACz4AIAAoAgBBgICAgHhHBEAgASAAKAIEIAAoAggQSg8LIAEoAgAgASgCBCAAKAIMKAIAIgAoAgAgACgCBBAVCzgAAkAgAkGAgMQARg0AIAAgAiABKAIQEQEARQ0AQQEPCyADRQRAQQAPCyAAIANBACABKAIMEQIACy0AAkAgA2lBAUcgAUGAgICAeCADa0tyDQAgACABIAMgAhBNIgBFDQAgAA8LAAssAQF/IwBBEGsiASQAIAEgAUEPaq1CgICAgLAGhDcDAEGlgcAAIAEgABAvAAvAAQEEfyMAQRBrIgMkACMAQSBrIgIkACACIAE2AhQgAiAANgIQIAIgAkEQaq1CgICAgBCENwMYIAJBBGogAkEYahAXIAEEQCAAIAFBARBSCyACKAIIIQACQCACKAIEIgUgAigCDCIETQRAIAAhAQwBCyAERQRAQQEhASAAIAVBARBSDAELIAAgBUEBIAQQTSIBDQBBASAEEEMACyADIAQ2AgQgAyABNgIAIAJBIGokACADKAIAIAMoAgQgA0EQaiQACx0AIABFBEAQWAALIAAgAiADIAQgBSABKAIQEQ0ACxsAIABFBEAQWAALIAAgAiADIAQgASgCEBEOAAsbACAARQRAEFgACyAAIAIgAyAEIAEoAhARBgALGwAgAEUEQBBYAAsgACACIAMgBCABKAIQERcACxsAIABFBEAQWAALIAAgAiADIAQgASgCEBEZAAsbACAARQRAEFgACyAAIAIgAyAEIAEoAhARGwALJwEBfyAAKAIAIgFBgICAgHhyQYCAgIB4RwRAIAAoAgQgAUEBEFILC4MGAgZ/AW8jAEEQayIEJAAgBEEIaiEFIwBBMGsiASQAQcySwAAtAABBA0cEQCABQQE6ABQgAUEUaiEAAkACQAJAAkACQEHMksAALQAAQQFrDgMBAwQAC0HMksAAQQI6AAAgAC0AACAAQQA6AABFDQECQAJAAkBB+JLAACgCAEH/////B3EEQEHgksAAKAIADQELQeySwAAoAgANAUH0ksAAKAIAIQBB9JLAAEGsiMAANgIAQfCSwAAoAgAhAkHwksAAQQE2AgACQCACRQ0AIAAoAgAiAwRAIAIgAxEDAAsgACgCBCIDRQ0AIAIgAyAAKAIIEFILDAILQbSNwABB6QBB6I3AABAvCwALQcySwABBAzoAAAwDC0GAgMAAQdUAQcSIwAAQLwALQfSPwABBK0GciMAAEEgAC0GqgMAAQfEAQcSIwAAQLwALCyABQQQ2AiQgAUHUiMAANgIgIAEgAUEgaq1CgICAgBCENwMoIAFBFGogAUEoahAXIAEoAhQhAiABKAIYIgMgASgCHBAQIQYQGiIAIAYmASABIAA2AiggAgRAIAMgAkEBEFILIAFBKGooAgAlARAGIABBhAFPBEAgABAnC0HYiMAAQQoQBEHYiMAAQQoQBQJ/QdCSwAAtAAAEQEHUksAAKAIAEFEMAQtBgJLAACgCACEAQYCSwABBADYCAAJAIAAEQCAAEQUAIQBB0JLAAC0AAA0BQdSSwAAgADYCAEHQksAAQQE6AAAgABBRDAILQeqKwABB1QBBlIvAABAvAAsgAEGDAUsEQCAAECcLQZiKwABBHUGoisAAEC8ACyIAJQEQAyICIABBhAFJckUEQCAAECcLIAFBCGoiAyAANgIEIAMgAkEARzYCAAJAIAEoAghBAXEEQCABKAIMIgBBhAFPBEAgABAnCyAFQQA2AgAgAUEwaiQADAELIwBBEGsiASQAIAFBGTYCBCABQeKIwAA2AgAgASABrUKAgICAwAaENwMIQaWBwAAgAUEIakH8iMAAEC8ACyAEQRBqJAALGQAgAEUEQBBYAAsgACACIAMgASgCEBEEAAsXACAARQRAEFgACyAAIAIgASgCEBEBAAsZAQF/IAAoAgAiAQRAIAAoAgQgAUEBEFILCx8AIABBCGpBrIzAACkCADcCACAAQaSMwAApAgA3AgALHwAgAEEIakGcjMAAKQIANwIAIABBlIzAACkCADcCAAsdACAABEAgACABEFoAC0GojsAAQSNBvI7AABAvAAsXAQF/IAAQCSIBNgIEIAAgAUEARzYCAAsXAQF/IAAQCiIBNgIEIAAgAUEARzYCAAsXAQF/IAAQCyIBNgIEIAAgAUEARzYCAAsXAQF/IAAQDCIBNgIEIAAgAUEARzYCAAsRACAAIAFBAXRBAXIgAhAvAAsPACABBEAgACABIAIQUgsLFgAgACgCACABIAIgACgCBCgCDBECAAsUACAAKAIAIAEgACgCBCgCDBEBAAsQACABIAAoAgAgACgCBBAUC+cGAQV/An8CQAJAAkACQAJAAkACQCAAQQRrIgcoAgAiCEF4cSIEQQRBCCAIQQNxIgUbIAFqTwRAIAVBACABQSdqIgYgBEkbDQECQCACQQlPBEAgAiADEBgiAg0BQQAMCgtBACECIANBzP97Sw0IQRAgA0ELakF4cSADQQtJGyEBIABBCGshBiAFRQRAIAZFIAFBgAJJciAEIAFrQYCACEsgASAET3JyDQcgAAwKCyAEIAZqIQUCQCABIARLBEAgBUGolsAAKAIARg0BQaSWwAAoAgAgBUcEQCAFKAIEIghBAnENCSAIQXhxIgggBGoiBCABSQ0JIAUgCBAZIAQgAWsiBUEQTwRAIAcgASAHKAIAQQFxckECcjYCACABIAZqIgEgBUEDcjYCBCAEIAZqIgQgBCgCBEEBcjYCBCABIAUQFgwJCyAHIAQgBygCAEEBcXJBAnI2AgAgBCAGaiIBIAEoAgRBAXI2AgQMCAtBnJbAACgCACAEaiIEIAFJDQgCQCAEIAFrIgVBD00EQCAHIAhBAXEgBHJBAnI2AgAgBCAGaiIBIAEoAgRBAXI2AgRBACEFQQAhAQwBCyAHIAEgCEEBcXJBAnI2AgAgASAGaiIBIAVBAXI2AgQgBCAGaiIEIAU2AgAgBCAEKAIEQX5xNgIEC0GklsAAIAE2AgBBnJbAACAFNgIADAcLIAQgAWsiBEEPTQ0GIAcgASAIQQFxckECcjYCACABIAZqIgEgBEEDcjYCBCAFIAUoAgRBAXI2AgQgASAEEBYMBgtBoJbAACgCACAEaiIEIAFLDQQMBgsgAyABIAEgA0sbIgMEQCACIAAgA/wKAAALIAcoAgAiA0F4cSIHIAFBBEEIIANBA3EiAxtqSQ0CIANFIAYgB09yDQZB9IzAAEEuQaSNwAAQSAALQbSMwABBLkHkjMAAEEgAC0H0jMAAQS5BpI3AABBIAAtBtIzAAEEuQeSMwAAQSAALIAcgASAIQQFxckECcjYCACABIAZqIgUgBCABayIBQQFyNgIEQaCWwAAgATYCAEGolsAAIAU2AgALIAZFDQAgAAwDCyADEBEiAUUNASADQXxBeCAHKAIAIgJBA3EbIAJBeHFqIgIgAiADSxsiAgRAIAEgACAC/AoAAAsgASECCyAAEBMLIAILCxYAQdySwAAgADYCAEHYksAAQQE2AgALEwAgAEH4jcAANgIEIAAgATYCAAsQACABIAAoAgAgACgCBBBKCxABAX8QGiIBIAAlASYBIAELXwEBfwJAAkAgAEEEaygCACICQXhxIgNBBEEIIAJBA3EiAhsgAWpPBEAgAkEAIAMgAUEnaksbDQEgABATDAILQbSMwABBLkHkjMAAEEgAC0H0jMAAQS5BpI3AABBIAAsLDwAgAEGYicAAIAEgAhAVCw8AIABBxIvAACABIAIQFQsPACAAQcyOwAAgASACEBULGQACfyABQQlPBEAgASAAEBgMAQsgABARCwsNACABQYiKwABBBRBKCwwAQbiKwABBMhANAAsMACAAIAEpAgA3AwALPQEBfyMAQRBrIgIkACACIAE2AgwgAiAANgIIIAJBCGoiACgCACAAKAIEQeiSwAAoAgAiAEEcIAAbEQAAAAsNACABQdyPwABBBRBKCw0AIAFB55HAAEEYEBQLDABBwJbAAEEBOgAACwkAIABBADYCAAuXBgMGfwF+AW8CQCMAQTBrIgIkACACQQA2AhwgAkKAgICAEDcCFCACQZiJwAA2AiQgAkKggICABjcCKCACIAJBFGo2AiAjAEEwayIFJABBASEGAkAgAkEgaiIEQYiOwABBDBBKDQAgBCgCBCEHIAQoAgAgBSABKAIIIgMpAgA3AgggBSADQQxqrUKAgICA0AOENwMgIAUgA0EIaq1CgICAgNADhDcDGCAFIAVBCGqtQoCAgIDgA4Q3AxAgB0HigMAAIAVBEGoiAxAVDQAgAyABKAIAIgAgASgCBCgCDCIHEQAAIAAhAQJAIAUpAxBC7bqtts2F1PXjAIUgBSkDGEL4gpm9le7Gxbl/hYRQBH9BBAUgAyAAIAcRAAAgBSkDEEL13JnNkqKa5nSFIAUpAxhCrpaizJPiq4k1hYRCAFINASAAQQRqIQFBCAsgAGooAgAhByABKAIAIQAgBEGUjsAAQQIQSg0BIAQgACAHEEoNAQtBACEGCyAFQTBqJAACQCAGRQRAIAJBEGogAkEcaigCACIBNgIAIAIgAikCFCIINwMIIAinIgMgAWtBCU0EQCACQQhqIAFBChAlIAIoAgghAyACKAIQIQELIAIoAgwiBCABaiIAQYyJwAApAAA3AAAgAEEIakGUicAALwAAOwAAIAIgAUEKaiIBNgIQEAAhCRAaIgAgCSYBIAJBIGogACUBEAEgAigCICEHAkACQCACKAIkIgYgAyABa0sEQCACQQhqIAEgBhAlIAIoAgghAyACKAIMIQQgAigCECEBDAELIAZFDQELIAZFDQAgASAEaiAHIAb8CgAACyACIAEgBmoiATYCECADIAFrQQFNBEAgAkEIaiABQQIQJSACKAIMIQQgAigCECEBCyABIARqQYoUOwAAIAIgAUECaiIDNgIQIAMgAigCCCIBSQRAIAQgAUEBIAMQTSIERQ0CCyAEIAMQAiAGBEAgByAGQQEQUgsgAEGEAU8EQCAAECcLIAJBMGokAAwCC0HAicAAQTcgAkEIakGwicAAQfiJwAAQKAALQQEgAxBDAAsLBgAQDxA9CwvEEgYAQYCAwAALqQhPbmNlIGluc3RhbmNlIGhhcyBwcmV2aW91c2x5IGJlZW4gcG9pc29uZWRvbmUtdGltZSBpbml0aWFsaXphdGlvbiBtYXkgbm90IGJlIHBlcmZvcm1lZCByZWN1cnNpdmVsecABOsABOsAAIGluZGV4IG91dCBvZiBib3VuZHM6IHRoZSBsZW4gaXMgwBIgYnV0IHRoZSBpbmRleCBpcyDAAMACOiDAAC9ydXN0Yy80NzQyNzY5NjFmNDhiMGQwNWY0ZWEyNjBiYTQwMDA5NmIwMjc1ODRlL2xpYnJhcnkvYWxsb2Mvc3JjL2ZtdC5ycwAvcnVzdGMvNDc0Mjc2OTYxZjQ4YjBkMDVmNGVhMjYwYmE0MDAwOTZiMDI3NTg0ZS9saWJyYXJ5L2NvcmUvc3JjL2ZtdC9udW0ucnMAQzpcVXNlcnNcOVwucnVzdHVwXHRvb2xjaGFpbnNcbmlnaHRseS14ODZfNjQtcGMtd2luZG93cy1tc3ZjXGxpYi9ydXN0bGliL3NyYy9ydXN0XGxpYnJhcnkvYWxsb2Mvc3JjL3N0cmluZy5ycwAvcnVzdGMvNDc0Mjc2OTYxZjQ4YjBkMDVmNGVhMjYwYmE0MDAwOTZiMDI3NTg0ZS9saWJyYXJ5L3N0ZC9zcmMvcGFuaWNraW5nLnJzAEM6XFVzZXJzXDlcLmNhcmdvXHJlZ2lzdHJ5XHNyY1xpbmRleC5jcmF0ZXMuaW8tMTk0OWNmOGM2YjViNTU3Zlx3YXNtLWJpbmRnZW4tMC4yLjEwOFxzcmNcZXh0ZXJucmVmLnJzAEM6XFVzZXJzXDlcLnJ1c3R1cFx0b29sY2hhaW5zXG5pZ2h0bHkteDg2XzY0LXBjLXdpbmRvd3MtbXN2Y1xsaWIvcnVzdGxpYi9zcmMvcnVzdFxsaWJyYXJ5L3N0ZC9zcmMvc3luYy9vbmNlLnJzAC9ydXN0Yy80NzQyNzY5NjFmNDhiMGQwNWY0ZWEyNjBiYTQwMDA5NmIwMjc1ODRlL2xpYnJhcnkvYWxsb2Mvc3JjL3Jhd192ZWMvbW9kLnJzAC9ydXN0L2RlcHMvZGxtYWxsb2MtMC4yLjExL3NyYy9kbG1hbGxvYy5ycwBDOlxVc2Vyc1w5XC5jYXJnb1xyZWdpc3RyeVxzcmNcaW5kZXguY3JhdGVzLmlvLTE5NDljZjhjNmI1YjU1N2ZcY29uc29sZV9lcnJvcl9wYW5pY19ob29rLTAuMS43XHNyY1xsaWIucnMAQzpcVXNlcnNcOVwuY2FyZ29ccmVnaXN0cnlcc3JjXGluZGV4LmNyYXRlcy5pby0xOTQ5Y2Y4YzZiNWI1NTdmXG9uY2VfY2VsbC0xLjIxLjNcc3JjXGxpYi5ycwAHSGVsbG8sIMABIQAAAF0CEABuAAAAnwAAADIAQbSIwAALeQEAAAACAAAAAwAAAAQAAABIAxAAaQAAAJUAAAAOAAAAbmFtZXRlc3QgbGFiZWxubyBnbG9iYWwgYHdpbmRvd2AgZXhpc3RzAAMEEAAKAAAAHQAAABsAAAAKClN0YWNrOgoKAAAFAAAADAAAAAQAAAAGAAAABwAAAAgAQbiJwAALqQUBAAAACQAAAGEgRGlzcGxheSBpbXBsZW1lbnRhdGlvbiByZXR1cm5lZCBhbiBlcnJvciB1bmV4cGVjdGVkbHkAPAEQAG0AAABmCwAADgAAAEVycm9ycmV0dXJuIHRoaXNyZWVudHJhbnQgaW5pdAAAsgMQAFsAAAB6AgAADQAAAGNsb3N1cmUgaW52b2tlZCByZWN1cnNpdmVseSBvciBhZnRlciBiZWluZyBkcm9wcGVkTGF6eSBpbnN0YW5jZSBoYXMgcHJldmlvdXNseSBiZWVuIHBvaXNvbmVksgMQAFsAAAAIAwAAGQAAAPcBEABlAAAAfwAAABEAAAD3ARAAZQAAAIwAAAARAAAAHwAAAAwAAAAEAAAAIAAAACEAAAAiAAAAAAAAAAgAAAAEAAAAIwAAACQAAAAlAAAAJgAAACcAAAAQAAAABAAAACgAAAApAAAAKgAAACsAAABtXcvWLFDrY3hBpldxG4u5dW6mKRFpzPQui4g5Ea8SNWFzc2VydGlvbiBmYWlsZWQ6IHBzaXplID49IHNpemUgKyBtaW5fb3ZlcmhlYWQAAB0DEAAqAAAAsQQAAAkAAABhc3NlcnRpb24gZmFpbGVkOiBwc2l6ZSA8PSBzaXplICsgbWF4X292ZXJoZWFkAAAdAxAAKgAAALcEAAANAAAAY2Fubm90IG1vZGlmeSB0aGUgcGFuaWMgaG9vayBmcm9tIGEgcGFuaWNraW5nIHRocmVhZKoBEABMAAAAkAAAAAkAAAAAAAAACAAAAAQAAAAsAAAAcGFuaWNrZWQgYXQgOgoAAB8AAAAMAAAABAAAAC0AAABjYXBhY2l0eSBvdmVyZmxvdwAAAMwCEABQAAAAHAAAAAUAAAAuAAAADAAAAAQAAAAvAAAAMAAAADEAQeyOwAALkwMBAAAAMgAAAGEgZm9ybWF0dGluZyB0cmFpdCBpbXBsZW1lbnRhdGlvbiByZXR1cm5lZCBhbiBlcnJvciB3aGVuIHRoZSB1bmRlcmx5aW5nIHN0cmVhbSBkaWQgbm90AACnABAASAAAAIoCAAAOAAAARXJyb3IAAADwABAASwAAAFcCAAAFAAAAY2FsbGVkIGBPcHRpb246OnVud3JhcCgpYCBvbiBhIGBOb25lYCB2YWx1ZTAwMDEwMjAzMDQwNTA2MDcwODA5MTAxMTEyMTMxNDE1MTYxNzE4MTkyMDIxMjIyMzI0MjUyNjI3MjgyOTMwMzEzMjMzMzQzNTM2MzczODM5NDA0MTQyNDM0NDQ1NDY0NzQ4NDk1MDUxNTI1MzU0NTU1NjU3NTg1OTYwNjE2MjYzNjQ2NTY2Njc2ODY5NzA3MTcyNzM3NDc1NzY3Nzc4Nzk4MDgxODI4Mzg0ODU4Njg3ODg4OTkwOTE5MjkzOTQ5NTk2OTc5ODk5UmVmQ2VsbCBhbHJlYWR5IGJvcnJvd2VkAEGAksAACzEWAAAAAgAAAAAAAAAXAAAAAgAAAAAAAAAYAAAAAgAAAAAAAAAZAAAAAgAAAAAAAAAaAEG8ksAACwEEAIQBCXByb2R1Y2VycwIIbGFuZ3VhZ2UBBFJ1c3QADHByb2Nlc3NlZC1ieQMFcnVzdGMlMS45NS4wLW5pZ2h0bHkgKDQ3NDI3Njk2MSAyMDI2LTAxLTI2KQZ3YWxydXMGMC4yNC40DHdhc20tYmluZGdlbhMwLjIuMTA4IChhNzg4ZjU4ZjkpAGsPdGFyZ2V0X2ZlYXR1cmVzBisPbXV0YWJsZS1nbG9iYWxzKxNub250cmFwcGluZy1mcHRvaW50KwtidWxrLW1lbW9yeSsIc2lnbi1leHQrD3JlZmVyZW5jZS10eXBlcysKbXVsdGl2YWx1ZQ==";

    // 3. ВСПОМОГАТЕЛЬНАЯ ФУНКЦИЯ (Base64 -> Uint8Array)
    function base64ToUint8Array(base64) {
        const binary_string = window.atob(base64);
        const len = binary_string.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes;
    }

    // 4. ЗАПУСК
    async function run() {
        // Декодируем байты
        const wasmBytes = base64ToUint8Array(WASM_BASE64);

        // Инициализируем wasm-bindgen, передавая байты напрямую
        // Обратите внимание: при target no-modules функция называется wasm_bindgen
        await wasm_bindgen(wasmBytes);

        console.log("Wasm loaded!");

        // Теперь можно вызывать ваши функции
        // Они доступны как методы объекта wasm_bindgen
        wasm_bindgen.greet_and_log("Tampermonkey User");

        // Или так:
        let msg = wasm_bindgen.greet("World");
        console.log("Result from Rust:", msg);
    }

    run();
})();