// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      2026-01-27
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*
// @match        https://*.google.com/*
// @match        http://*.skazanie.com/*
// @match        http://*.bbgam.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=google.com
// @grant        GM_xmlhttpRequest
// ==/UserScript==

(function () {
    'use strict';

    // 1. ВСТАВЬТЕ СЮДА СОДЕРЖИМОЕ ФАЙЛА pkg/your_project.js
    // (Скопируйте всё из .js файла, сгенерированного wasm-pack --target no-modules)
    let wasm_bindgen = (function (exports) {
        let script_src;
        if (typeof document !== 'undefined' && document.currentScript !== null) {
            script_src = new URL(document.currentScript.src, location.href).toString();
        }

        /**
         * @param {string} name
         * @returns {string}
         */
        function greet(name) {
            let deferred2_0;
            let deferred2_1;
            try {
                const ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
                const len0 = WASM_VECTOR_LEN;
                const ret = wasm.greet(ptr0, len0);
                deferred2_0 = ret[0];
                deferred2_1 = ret[1];
                return getStringFromWasm0(ret[0], ret[1]);
            } finally {
                wasm.__wbindgen_free(deferred2_0, deferred2_1, 1);
            }
        }
        exports.greet = greet;

        /**
         * @param {string} name
         */
        function greet_and_log(name) {
            const ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
            const len0 = WASM_VECTOR_LEN;
            const ret = wasm.greet_and_log(ptr0, len0);
            if (ret[1]) {
                throw takeFromExternrefTable0(ret[0]);
            }
        }
        exports.greet_and_log = greet_and_log;

        function __wbg_get_imports() {
            const import0 = {
                __proto__: null,
                __wbg___wbindgen_throw_be289d5034ed271b: function (arg0, arg1) {
                    throw new Error(getStringFromWasm0(arg0, arg1));
                },
                __wbg_log_6b5ca2e6124b2808: function (arg0) {
                    console.log(arg0);
                },
                __wbg_timeEnd_4b7c4393c92f755c: function (arg0, arg1) {
                    console.timeEnd(getStringFromWasm0(arg0, arg1));
                },
                __wbg_time_fe7e4750af05fa96: function (arg0, arg1) {
                    console.time(getStringFromWasm0(arg0, arg1));
                },
                __wbindgen_cast_0000000000000001: function (arg0, arg1) {
                    // Cast intrinsic for `Ref(String) -> Externref`.
                    const ret = getStringFromWasm0(arg0, arg1);
                    return ret;
                },
                __wbindgen_init_externref_table: function () {
                    const table = wasm.__wbindgen_externrefs;
                    const offset = table.grow(4);
                    table.set(0, undefined);
                    table.set(offset + 0, undefined);
                    table.set(offset + 1, null);
                    table.set(offset + 2, true);
                    table.set(offset + 3, false);
                },
            };
            return {
                __proto__: null,
                "./wasm_bg.js": import0,
            };
        }

        function getStringFromWasm0(ptr, len) {
            ptr = ptr >>> 0;
            return decodeText(ptr, len);
        }

        let cachedUint8ArrayMemory0 = null;
        function getUint8ArrayMemory0() {
            if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
                cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
            }
            return cachedUint8ArrayMemory0;
        }

        function passStringToWasm0(arg, malloc, realloc) {
            if (realloc === undefined) {
                const buf = cachedTextEncoder.encode(arg);
                const ptr = malloc(buf.length, 1) >>> 0;
                getUint8ArrayMemory0().subarray(ptr, ptr + buf.length).set(buf);
                WASM_VECTOR_LEN = buf.length;
                return ptr;
            }

            let len = arg.length;
            let ptr = malloc(len, 1) >>> 0;

            const mem = getUint8ArrayMemory0();

            let offset = 0;

            for (; offset < len; offset++) {
                const code = arg.charCodeAt(offset);
                if (code > 0x7F) break;
                mem[ptr + offset] = code;
            }
            if (offset !== len) {
                if (offset !== 0) {
                    arg = arg.slice(offset);
                }
                ptr = realloc(ptr, len, len = offset + arg.length * 3, 1) >>> 0;
                const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
                const ret = cachedTextEncoder.encodeInto(arg, view);

                offset += ret.written;
                ptr = realloc(ptr, len, offset, 1) >>> 0;
            }

            WASM_VECTOR_LEN = offset;
            return ptr;
        }

        function takeFromExternrefTable0(idx) {
            const value = wasm.__wbindgen_externrefs.get(idx);
            wasm.__externref_table_dealloc(idx);
            return value;
        }

        let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
        cachedTextDecoder.decode();
        function decodeText(ptr, len) {
            return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
        }

        const cachedTextEncoder = new TextEncoder();

        if (!('encodeInto' in cachedTextEncoder)) {
            cachedTextEncoder.encodeInto = function (arg, view) {
                const buf = cachedTextEncoder.encode(arg);
                view.set(buf);
                return {
                    read: arg.length,
                    written: buf.length
                };
            };
        }

        let WASM_VECTOR_LEN = 0;

        let wasmModule, wasm;
        function __wbg_finalize_init(instance, module) {
            wasm = instance.exports;
            wasmModule = module;
            cachedUint8ArrayMemory0 = null;
            wasm.__wbindgen_start();
            return wasm;
        }

        async function __wbg_load(module, imports) {
            if (typeof Response === 'function' && module instanceof Response) {
                if (typeof WebAssembly.instantiateStreaming === 'function') {
                    try {
                        return await WebAssembly.instantiateStreaming(module, imports);
                    } catch (e) {
                        const validResponse = module.ok && expectedResponseType(module.type);

                        if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
                            console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                        } else { throw e; }
                    }
                }

                const bytes = await module.arrayBuffer();
                return await WebAssembly.instantiate(bytes, imports);
            } else {
                const instance = await WebAssembly.instantiate(module, imports);

                if (instance instanceof WebAssembly.Instance) {
                    return { instance, module };
                } else {
                    return instance;
                }
            }

            function expectedResponseType(type) {
                switch (type) {
                    case 'basic': case 'cors': case 'default': return true;
                }
                return false;
            }
        }

        function initSync(module) {
            if (wasm !== undefined) return wasm;


            if (module !== undefined) {
                if (Object.getPrototypeOf(module) === Object.prototype) {
                    ({ module } = module)
                } else {
                    console.warn('using deprecated parameters for `initSync()`; pass a single object instead')
                }
            }

            const imports = __wbg_get_imports();
            if (!(module instanceof WebAssembly.Module)) {
                module = new WebAssembly.Module(module);
            }
            const instance = new WebAssembly.Instance(module, imports);
            return __wbg_finalize_init(instance, module);
        }

        async function __wbg_init(module_or_path) {
            if (wasm !== undefined) return wasm;


            if (module_or_path !== undefined) {
                if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
                    ({ module_or_path } = module_or_path)
                } else {
                    console.warn('using deprecated parameters for the initialization function; pass a single object instead')
                }
            }

            if (module_or_path === undefined && script_src !== undefined) {
                module_or_path = script_src.replace(/\.js$/, "_bg.wasm");
            }
            const imports = __wbg_get_imports();

            if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
                module_or_path = fetch(module_or_path);
            }

            const { instance, module } = await __wbg_load(await module_or_path, imports);

            return __wbg_finalize_init(instance, module);
        }

        return Object.assign(__wbg_init, { initSync }, exports);
    })({ __proto__: null });

    // 2. ВАША BASE64 СТРОКА (из шага 2)
    const WASM_BASE64 = "AGFzbQEAAAABmwEXYAJ/fwBgAn9/AX9gA39/fwF/YAF/AGADf39/AGAEf39/fwF/YAACf39gBX9/f39/AGAAAGAGf39/f39/AGACf38Cf39gBX9/f39/AX9gBH9/f38AYAFvAGACf38Bb2ABfwF/YAZ/f39/f38Bf2AFf398f38AYAR/fH9/AGAFf399f38AYAR/fX9/AGAFf39+f38AYAR/fn9/AAKaAgYMLi93YXNtX2JnLmpzG19fd2JnX3RpbWVfZmU3ZTQ3NTBhZjA1ZmE5NgAADC4vd2FzbV9iZy5qcx5fX3diZ190aW1lRW5kXzRiN2M0MzkzYzkyZjc1NWMAAAwuL3dhc21fYmcuanMaX193YmdfbG9nXzZiNWNhMmU2MTI0YjI4MDgADQwuL3dhc21fYmcuanMnX193YmdfX193YmluZGdlbl90aHJvd19iZTI4OWQ1MDM0ZWQyNzFiAAAMLi93YXNtX2JnLmpzH19fd2JpbmRnZW5faW5pdF9leHRlcm5yZWZfdGFibGUACAwuL3dhc21fYmcuanMgX193YmluZGdlbl9jYXN0XzAwMDAwMDAwMDAwMDAwMDEADgM+PQ8DAgUAAAEAAAEBAAcJCQQABAMCAgAEAQEFAwoKEAcLERMVAwwCAwAAAAAEAgEBBQABAAICAQgAAAEBAAAECQJwAScnbwCAAQUDAQARBgkBfwFBgIDAAAsHpAEJBm1lbW9yeQIABWdyZWV0ACENZ3JlZXRfYW5kX2xvZwAiFV9fd2JpbmRnZW5fZXh0ZXJucmVmcwEBEV9fd2JpbmRnZW5fbWFsbG9jAB0SX193YmluZGdlbl9yZWFsbG9jAB8PX193YmluZGdlbl9mcmVlADEZX19leHRlcm5yZWZfdGFibGVfZGVhbGxvYwAYEF9fd2JpbmRnZW5fc3RhcnQABAksAQBBAQsmNCUTJiQnKCokJCUjKwVBLBkPOTcbNj0pHhEWQi4tLBoQOj9AMzQMAQMKsXM9ySUCCX8BfiMAQRBrIggkAAJAAkACQAJAAkAgAEH1AU8EQCAAQcz/e0sEQEEAIQAMBgsgAEELaiICQXhxIQVB2IrAACgCACIJRQ0EQR8hBkEAIAVrIQMgAEH0//8HTQRAIAVBJiACQQh2ZyIAa3ZBAXEgAEEBdGtBPmohBgsgBkECdEG8h8AAaigCACICRQRAQQAhAAwCCyAFQRkgBkEBdmtBACAGQR9HG3QhBEEAIQADQAJAIAIoAgRBeHEiByAFSQ0AIAcgBWsiByADTw0AIAIhASAHIgMNAEEAIQMgASEADAQLIAIoAhQiByAAIAcgAiAEQR12QQRxaigCECICRxsgACAHGyEAIARBAXQhBCACDQALDAELAkACQAJAAkACQEHUisAAKAIAIgRBECAAQQtqQfgDcSAAQQtJGyIFQQN2IgB2IgFBA3EEQCABQX9zQQFxIABqIgdBA3QiAUHMiMAAaiIAIAFB1IjAAGooAgAiAigCCCIDRg0BIAMgADYCDCAAIAM2AggMAgsgBUHcisAAKAIATQ0IIAENAkHYisAAKAIAIgBFDQggAGhBAnRBvIfAAGooAgAiAigCBEF4cSAFayEDIAIhAQNAAkAgASgCECIADQAgASgCFCIADQAgAigCGCEGAkACQCACIAIoAgwiAEYEQCACQRRBECACKAIUIgAbaigCACIBDQFBACEADAILIAIoAggiASAANgIMIAAgATYCCAwBCyACQRRqIAJBEGogABshBANAIAQhByABIgBBFGogAEEQaiAAKAIUIgEbIQQgAEEUQRAgARtqKAIAIgENAAsgB0EANgIACyAGRQ0GAkAgAigCHEECdEG8h8AAaiIBKAIAIAJHBEAgAiAGKAIQRwRAIAYgADYCFCAADQIMCQsgBiAANgIQIAANAQwICyABIAA2AgAgAEUNBgsgACAGNgIYIAIoAhAiAQRAIAAgATYCECABIAA2AhgLIAIoAhQiAUUNBiAAIAE2AhQgASAANgIYDAYLIAAoAgRBeHEgBWsiASADIAEgA0kiARshAyAAIAIgARshAiAAIQEMAAsAC0HUisAAIARBfiAHd3E2AgALIAJBCGohACACIAFBA3I2AgQgASACaiIBIAEoAgRBAXI2AgQMBwsCQEECIAB0IgJBACACa3IgASAAdHFoIgdBA3QiAUHMiMAAaiICIAFB1IjAAGooAgAiACgCCCIDRwRAIAMgAjYCDCACIAM2AggMAQtB1IrAACAEQX4gB3dxNgIACyAAIAVBA3I2AgQgACAFaiIGIAEgBWsiB0EBcjYCBCAAIAFqIAc2AgBB3IrAACgCACICBEBB5IrAACgCACEBAkBB1IrAACgCACIEQQEgAkEDdnQiA3FFBEBB1IrAACADIARyNgIAIAJBeHFBzIjAAGoiAyEEDAELIAJBeHEiAkHMiMAAaiEEIAJB1IjAAGooAgAhAwsgBCABNgIIIAMgATYCDCABIAQ2AgwgASADNgIICyAAQQhqIQBB5IrAACAGNgIAQdyKwAAgBzYCAAwGC0HYisAAQdiKwAAoAgBBfiACKAIcd3E2AgALAkACQCADQRBPBEAgAiAFQQNyNgIEIAIgBWoiByADQQFyNgIEIAMgB2ogAzYCAEHcisAAKAIAIgFFDQFB5IrAACgCACEAAkBB1IrAACgCACIEQQEgAUEDdnQiBnFFBEBB1IrAACAEIAZyNgIAIAFBeHFBzIjAAGoiBCEBDAELIAFBeHEiBEHMiMAAaiEBIARB1IjAAGooAgAhBAsgASAANgIIIAQgADYCDCAAIAE2AgwgACAENgIIDAELIAIgAyAFaiIAQQNyNgIEIAAgAmoiACAAKAIEQQFyNgIEDAELQeSKwAAgBzYCAEHcisAAIAM2AgALIAJBCGoiAEUNAwwECyAAIAFyRQRAQQAhAUECIAZ0IgBBACAAa3IgCXEiAEUNAyAAaEECdEG8h8AAaigCACEACyAARQ0BCwNAIAMgACgCBEF4cSICIAVrIgQgAyADIARLIgQbIAIgBUkiAhshAyABIAAgASAEGyACGyEBIAAoAhAiAgR/IAIFIAAoAhQLIgANAAsLIAFFDQAgBUHcisAAKAIAIgBNIAMgACAFa09xDQAgASgCGCEGAkACQCABIAEoAgwiAEYEQCABQRRBECABKAIUIgAbaigCACICDQFBACEADAILIAEoAggiAiAANgIMIAAgAjYCCAwBCyABQRRqIAFBEGogABshBANAIAQhByACIgBBFGogAEEQaiAAKAIUIgIbIQQgAEEUQRAgAhtqKAIAIgINAAsgB0EANgIACwJAIAZFDQACQAJAIAEoAhxBAnRBvIfAAGoiAigCACABRwRAIAEgBigCEEcEQCAGIAA2AhQgAA0CDAQLIAYgADYCECAADQEMAwsgAiAANgIAIABFDQELIAAgBjYCGCABKAIQIgIEQCAAIAI2AhAgAiAANgIYCyABKAIUIgJFDQEgACACNgIUIAIgADYCGAwBC0HYisAAQdiKwAAoAgBBfiABKAIcd3E2AgALAkAgA0EQTwRAIAEgBUEDcjYCBCABIAVqIgAgA0EBcjYCBCAAIANqIAM2AgAgA0GAAk8EQCAAIAMQDgwCCwJAQdSKwAAoAgAiAkEBIANBA3Z0IgRxRQRAQdSKwAAgAiAEcjYCACADQfgBcUHMiMAAaiIDIQIMAQsgA0H4AXEiBEHMiMAAaiECIARB1IjAAGooAgAhAwsgAiAANgIIIAMgADYCDCAAIAI2AgwgACADNgIIDAELIAEgAyAFaiIAQQNyNgIEIAAgAWoiACAAKAIEQQFyNgIECyABQQhqIgANAQsCQAJAAkACQAJAIAVB3IrAACgCACIBSwRAIAVB4IrAACgCACIATwRAIAhBBGohAAJ/IAVBr4AEakGAgHxxIgFBEHYgAUH//wNxQQBHaiIBQAAiBEF/RgRAQQAhAUEADAELIAFBEHQiAkEQayACIARBEHQiAUEAIAJrRhsLIQIgAEEANgIIIAAgAjYCBCAAIAE2AgAgCCgCBCIBRQRAQQAhAAwICyAIKAIMIQdB7IrAACAIKAIIIgRB7IrAACgCAGoiADYCAEHwisAAIABB8IrAACgCACICIAAgAksbNgIAAkACQEHoisAAKAIAIgIEQEG8iMAAIQADQCABIAAoAgAiAyAAKAIEIgZqRg0CIAAoAggiAA0ACwwCC0H4isAAKAIAIgBBACAAIAFNG0UEQEH4isAAIAE2AgALQfyKwABB/x82AgBByIjAACAHNgIAQcCIwAAgBDYCAEG8iMAAIAE2AgBB2IjAAEHMiMAANgIAQeCIwABB1IjAADYCAEHUiMAAQcyIwAA2AgBB6IjAAEHciMAANgIAQdyIwABB1IjAADYCAEHwiMAAQeSIwAA2AgBB5IjAAEHciMAANgIAQfiIwABB7IjAADYCAEHsiMAAQeSIwAA2AgBBgInAAEH0iMAANgIAQfSIwABB7IjAADYCAEGIicAAQfyIwAA2AgBB/IjAAEH0iMAANgIAQZCJwABBhInAADYCAEGEicAAQfyIwAA2AgBBmInAAEGMicAANgIAQYyJwABBhInAADYCAEGUicAAQYyJwAA2AgBBoInAAEGUicAANgIAQZyJwABBlInAADYCAEGoicAAQZyJwAA2AgBBpInAAEGcicAANgIAQbCJwABBpInAADYCAEGsicAAQaSJwAA2AgBBuInAAEGsicAANgIAQbSJwABBrInAADYCAEHAicAAQbSJwAA2AgBBvInAAEG0icAANgIAQciJwABBvInAADYCAEHEicAAQbyJwAA2AgBB0InAAEHEicAANgIAQcyJwABBxInAADYCAEHYicAAQcyJwAA2AgBB4InAAEHUicAANgIAQdSJwABBzInAADYCAEHoicAAQdyJwAA2AgBB3InAAEHUicAANgIAQfCJwABB5InAADYCAEHkicAAQdyJwAA2AgBB+InAAEHsicAANgIAQeyJwABB5InAADYCAEGAisAAQfSJwAA2AgBB9InAAEHsicAANgIAQYiKwABB/InAADYCAEH8icAAQfSJwAA2AgBBkIrAAEGEisAANgIAQYSKwABB/InAADYCAEGYisAAQYyKwAA2AgBBjIrAAEGEisAANgIAQaCKwABBlIrAADYCAEGUisAAQYyKwAA2AgBBqIrAAEGcisAANgIAQZyKwABBlIrAADYCAEGwisAAQaSKwAA2AgBBpIrAAEGcisAANgIAQbiKwABBrIrAADYCAEGsisAAQaSKwAA2AgBBwIrAAEG0isAANgIAQbSKwABBrIrAADYCAEHIisAAQbyKwAA2AgBBvIrAAEG0isAANgIAQdCKwABBxIrAADYCAEHEisAAQbyKwAA2AgBB6IrAACABQQ9qQXhxIgBBCGsiAjYCAEHMisAAQcSKwAA2AgBB4IrAACAEQShrIgQgASAAa2pBCGoiADYCACACIABBAXI2AgQgASAEakEoNgIEQfSKwABBgICAATYCAAwICyACIANJIAEgAk1yDQAgACgCDCIDQQFxDQAgA0EBdiAHRg0DC0H4isAAQfiKwAAoAgAiACABIAAgAUkbNgIAIAEgBGohA0G8iMAAIQACQAJAA0AgAyAAKAIAIgZHBEAgACgCCCIADQEMAgsLIAAoAgwiA0EBcQ0AIANBAXYgB0YNAQtBvIjAACEAA0ACQCACIAAoAgAiA08EQCACIAMgACgCBGoiBkkNAQsgACgCCCEADAELC0HoisAAIAFBD2pBeHEiAEEIayIDNgIAQeCKwAAgBEEoayIJIAEgAGtqQQhqIgA2AgAgAyAAQQFyNgIEIAEgCWpBKDYCBEH0isAAQYCAgAE2AgAgAiAGQSBrQXhxQQhrIgAgACACQRBqSRsiA0EbNgIEQbyIwAApAgAhCiADQRBqQcSIwAApAgA3AgAgA0EIaiIAIAo3AgBByIjAACAHNgIAQcCIwAAgBDYCAEG8iMAAIAE2AgBBxIjAACAANgIAIANBHGohAANAIABBBzYCACAAQQRqIgAgBkkNAAsgAiADRg0HIAMgAygCBEF+cTYCBCACIAMgAmsiAEEBcjYCBCADIAA2AgAgAEGAAk8EQCACIAAQDgwICwJAQdSKwAAoAgAiAUEBIABBA3Z0IgRxRQRAQdSKwAAgASAEcjYCACAAQfgBcUHMiMAAaiIAIQEMAQsgAEH4AXEiAEHMiMAAaiEBIABB1IjAAGooAgAhAAsgASACNgIIIAAgAjYCDCACIAE2AgwgAiAANgIIDAcLIAAgATYCACAAIAAoAgQgBGo2AgQgAUEPakF4cUEIayIEIAVBA3I2AgQgBkEPakF4cUEIayIDIAQgBWoiAGshBSADQeiKwAAoAgBGDQMgA0HkisAAKAIARg0EIAMoAgQiAkEDcUEBRgRAIAMgAkF4cSIBEA0gASAFaiEFIAEgA2oiAygCBCECCyADIAJBfnE2AgQgACAFQQFyNgIEIAAgBWogBTYCACAFQYACTwRAIAAgBRAODAYLAkBB1IrAACgCACIBQQEgBUEDdnQiAnFFBEBB1IrAACABIAJyNgIAIAVB+AFxQcyIwABqIgUhAwwBCyAFQfgBcSIBQcyIwABqIQMgAUHUiMAAaigCACEFCyADIAA2AgggBSAANgIMIAAgAzYCDCAAIAU2AggMBQtB4IrAACAAIAVrIgE2AgBB6IrAAEHoisAAKAIAIgAgBWoiAjYCACACIAFBAXI2AgQgACAFQQNyNgIEIABBCGohAAwGC0HkisAAKAIAIQACQCABIAVrIgJBD00EQEHkisAAQQA2AgBB3IrAAEEANgIAIAAgAUEDcjYCBCAAIAFqIgEgASgCBEEBcjYCBAwBC0HcisAAIAI2AgBB5IrAACAAIAVqIgQ2AgAgBCACQQFyNgIEIAAgAWogAjYCACAAIAVBA3I2AgQLIABBCGohAAwFCyAAIAQgBmo2AgRB6IrAAEHoisAAKAIAIgBBD2pBeHEiAUEIayICNgIAQeCKwABB4IrAACgCACAEaiIEIAAgAWtqQQhqIgE2AgAgAiABQQFyNgIEIAAgBGpBKDYCBEH0isAAQYCAgAE2AgAMAwtB6IrAACAANgIAQeCKwABB4IrAACgCACAFaiIBNgIAIAAgAUEBcjYCBAwBC0HkisAAIAA2AgBB3IrAAEHcisAAKAIAIAVqIgE2AgAgACABQQFyNgIEIAAgAWogATYCAAsgBEEIaiEADAELQQAhAEHgisAAKAIAIgEgBU0NAEHgisAAIAEgBWsiATYCAEHoisAAQeiKwAAoAgAiACAFaiICNgIAIAIgAUEBcjYCBCAAIAVBA3I2AgQgAEEIaiEACyAIQRBqJAAgAAuUBgEFfyAAQQhrIgEgAEEEaygCACIDQXhxIgBqIQICQAJAIANBAXENACADQQJxRQ0BIAEoAgAiAyAAaiEAIAEgA2siAUHkisAAKAIARgRAIAIoAgRBA3FBA0cNAUHcisAAIAA2AgAgAiACKAIEQX5xNgIEIAEgAEEBcjYCBCACIAA2AgAPCyABIAMQDQsCQAJAAkACQAJAIAIoAgQiA0ECcUUEQCACQeiKwAAoAgBGDQIgAkHkisAAKAIARg0DIAIgA0F4cSICEA0gASAAIAJqIgBBAXI2AgQgACABaiAANgIAIAFB5IrAACgCAEcNAUHcisAAIAA2AgAPCyACIANBfnE2AgQgASAAQQFyNgIEIAAgAWogADYCAAsgAEGAAkkNAiABIAAQDkEAIQFB/IrAAEH8isAAKAIAQQFrIgA2AgAgAA0EQcSIwAAoAgAiAARAA0AgAUEBaiEBIAAoAggiAA0ACwtB/IrAAEH/HyABIAFB/x9NGzYCAA8LQeiKwAAgATYCAEHgisAAQeCKwAAoAgAgAGoiADYCACABIABBAXI2AgRB5IrAACgCACABRgRAQdyKwABBADYCAEHkisAAQQA2AgALIABB9IrAACgCACIDTQ0DQeiKwAAoAgAiAkUNA0EAIQBB4IrAACgCACIEQSlJDQJBvIjAACEBA0AgAiABKAIAIgVPBEAgAiAFIAEoAgRqSQ0ECyABKAIIIQEMAAsAC0HkisAAIAE2AgBB3IrAAEHcisAAKAIAIABqIgA2AgAgASAAQQFyNgIEIAAgAWogADYCAA8LAkBB1IrAACgCACICQQEgAEEDdnQiA3FFBEBB1IrAACACIANyNgIAIABB+AFxQcyIwABqIgAhAgwBCyAAQfgBcSIAQcyIwABqIQIgAEHUiMAAaigCACEACyACIAE2AgggACABNgIMIAEgAjYCDCABIAA2AggPC0HEiMAAKAIAIgEEQANAIABBAWohACABKAIIIgENAAsLQfyKwABB/x8gACAAQf8fTRs2AgAgAyAETw0AQfSKwABBfzYCAAsLiAsBC38CQAJAIAAoAggiDUGAgIDAAXFFDQACQAJAAkACQCANQYCAgIABcQRAIAAvAQ4iBQ0BQQAhAgwCCyACQRBPBEACfwJAAkAgAiABQQNqQXxxIgQgAWsiA0kNACACIANrIgtBBEkNACABIARHBEAgASAEayIEQXxNBEADQCAFIAEgCWoiBywAAEG/f0pqIAdBAWosAABBv39KaiAHQQJqLAAAQb9/SmogB0EDaiwAAEG/f0pqIQUgCUEEaiIJDQALCyABIAlqIQgDQCAFIAgsAABBv39KaiEFIAhBAWohCCAEQQFqIgQNAAsLIAEgA2ohBAJAIAtBA3EiB0UNACAEIAtB/P///wdxaiIDLAAAQb9/SiEKIAdBAUYNACAKIAMsAAFBv39KaiEKIAdBAkYNACAKIAMsAAJBv39KaiEKCyALQQJ2IQwgBSAKaiEJA0AgBCEDIAxFDQJBwAEgDCAMQcABTxsiBkEDcSEKAkAgBkECdCILQfAHcSIERQRAQQAhCAwBCyADIARqIQdBACEIIAMhBQNAIAggBSgCACIEQX9zQQd2IARBBnZyQYGChAhxaiAFQQRqKAIAIgRBf3NBB3YgBEEGdnJBgYKECHFqIAVBCGooAgAiBEF/c0EHdiAEQQZ2ckGBgoQIcWogBUEMaigCACIEQX9zQQd2IARBBnZyQYGChAhxaiEIIAVBEGoiBSAHRw0ACwsgDCAGayEMIAMgC2ohBCAIQQh2Qf+B/AdxIAhB/4H8B3FqQYGABGxBEHYgCWohCSAKRQ0ACwJ/IAMgBkH8AXFBAnRqIgUoAgAiA0F/c0EHdiADQQZ2ckGBgoQIcSIEIApBAUYNABogBCAFKAIEIgNBf3NBB3YgA0EGdnJBgYKECHFqIgMgCkECRg0AGiADIAUoAggiA0F/c0EHdiADQQZ2ckGBgoQIcWoLIgNBCHZB/4EccSADQf+B/AdxakGBgARsQRB2IAlqIQkMAQtBACACRQ0BGiACQQNxIQQgAkEETwRAIAJBfHEhAwNAIAkgASAIaiIFLAAAQb9/SmogBUEBaiwAAEG/f0pqIAVBAmosAABBv39KaiAFQQNqLAAAQb9/SmohCSADIAhBBGoiCEcNAAsLIARFDQAgASAIaiEFA0AgCSAFLAAAQb9/SmohCSAFQQFqIQUgBEEBayIEDQALCyAJCyEGDAQLIAJFDQMgAkEDcSEHIAJBBE8EQCACQQxxIQMDQCAGIAEgBGoiBSwAAEG/f0pqIAVBAWosAABBv39KaiAFQQJqLAAAQb9/SmogBUEDaiwAAEG/f0pqIQYgAyAEQQRqIgRHDQALCyAHRQ0DIAEgBGohAwNAIAYgAywAAEG/f0pqIQYgA0EBaiEDIAdBAWsiBw0ACwwDCyABIAJqIQtBACECIAEhAyAFIQQDQCADIgcgC0YNAiACAn8gA0EBaiADLAAAIgJBAE4NABogA0ECaiACQWBJDQAaIANBA2ogAkFwSQ0AGiADQQRqCyIDIAdraiECIARBAWsiBA0ACwtBACEECyAFIARrIQYLIAYgAC8BDCIDTw0AIAMgBmshBUEAIQZBACEEAkACQAJAIA1BHXZBA3FBAWsOAgABAgsgBSEEDAELIAVB/v8DcUEBdiEECyANQf///wBxIQcgACgCBCEKIAAoAgAhCwNAIAZB//8DcSAEQf//A3FJBEBBASEDIAZBAWohBiALIAcgCigCEBEBAEUNAQwDCwtBASEDIAsgASACIAooAgwRAgANAUEAIQYgBSAEa0H//wNxIQEDQCAGQf//A3EiACABSSEDIAAgAU8NAiAGQQFqIQYgCyAHIAooAhARAQBFDQALDAELIAAoAgAgASACIAAoAgQoAgwRAgAhAwsgAwv7AwEIfyMAQRBrIgYkAAJ/AkAgA0EBcUUEQCACLQAAIgUNAUEADAILIAAgAiADQQF2IAEoAgwRAgAMAQsgASgCDCEKA0AgAkEBaiEEAkACQAJAAkAgBcBBAEgEQCAFQf8BcSIIQYABRg0BIAhBwAFHDQMgBiABNgIEIAYgADYCACAGQqCAgIAGNwIIIAMgB0EDdGoiAigCACAGIAIoAgQRAQBFDQJBAQwGCyAAIAQgBUH/AXEiAiAKEQIARQRAIAIgBGohAgwEC0EBDAULIAAgAkEDaiIEIAIvAAEiAiAKEQIARQRAIAIgBGohAgwDC0EBDAQLIAdBAWohByAEIQIMAQtBoICAgAYhCyAFQQFxBEAgAigAASELIAJBBWohBAtBACEIAn8gBUECcUUEQEEAIQkgBAwBCyAELwAAIQkgBEECagshAiAFQQRxBH8gAi8AACEIIAJBAmoFIAILIQQgBUEIcQR/IAQvAAAhByAEQQJqBSAECyECIAVBEHEEQCADIAlBA3RqLwEEIQkLIAYgBUEgcQR/IAMgCEEDdGovAQQFIAgLOwEOIAYgCTsBDCAGIAs2AgggBiABNgIEIAYgADYCAEEBIAMgB0EDdGoiBCgCACAGIAQoAgQRAQANAhogB0EBaiEHCyACLQAAIgUNAAtBAAsgBkEQaiQAC48EAQJ/IAAgAWohAgJAAkAgACgCBCIDQQFxDQAgA0ECcUUNASAAKAIAIgMgAWohASAAIANrIgBB5IrAACgCAEYEQCACKAIEQQNxQQNHDQFB3IrAACABNgIAIAIgAigCBEF+cTYCBCAAIAFBAXI2AgQgAiABNgIADAILIAAgAxANCwJAAkACQCACKAIEIgNBAnFFBEAgAkHoisAAKAIARg0CIAJB5IrAACgCAEYNAyACIANBeHEiAhANIAAgASACaiIBQQFyNgIEIAAgAWogATYCACAAQeSKwAAoAgBHDQFB3IrAACABNgIADwsgAiADQX5xNgIEIAAgAUEBcjYCBCAAIAFqIAE2AgALIAFBgAJPBEAgACABEA4PCwJAQdSKwAAoAgAiAkEBIAFBA3Z0IgNxRQRAQdSKwAAgAiADcjYCACABQfgBcUHMiMAAaiIBIQIMAQsgAUH4AXEiAUHMiMAAaiECIAFB1IjAAGooAgAhAQsgAiAANgIIIAEgADYCDCAAIAI2AgwgACABNgIIDwtB6IrAACAANgIAQeCKwABB4IrAACgCACABaiIBNgIAIAAgAUEBcjYCBCAAQeSKwAAoAgBHDQFB3IrAAEEANgIAQeSKwABBADYCAA8LQeSKwAAgADYCAEHcisAAQdyKwAAoAgAgAWoiATYCACAAIAFBAXI2AgQgACABaiABNgIACwvZAwEGfyMAQRBrIgQkAAJAAkACQAJAAkACQCABQQFxBEAgAUEBdiECDAELQbuCwAAtAAAiAkUNAUG7gsAAIQMDQCADQQFqIQMCQCACwEEASARAIAJB/wFxQYABRgRAIAUgAy8AACICaiEFIAIgA2pBAmohAwwCCyADIAJBA3FBGHciB0EFdEGAgICABHEgB0GAgICAAnEgB0GAgIAIcUEHdHJyQR12aiACQQF2QQJxaiACQQJ2QQJxaiEDIAVFIAZyIQYMAQsgAyACQf8BcSICaiEDIAIgBWohBQsgAy0AACICDQALQQAhAiAGIAVBEElxDQBBACEGIAVBAXQiAkEASA0ECyACDQELQQEhA0EAIQIMAQtBASEGIAJBARA7IgNFDQELIARBADYCCCAEIAM2AgQgBCACNgIAIARB0IXAAEG7gsAAIAEQCUUNASMAQSBrIgAkACAAQdYANgIEIABB+IXAADYCACAAQeiFwAA2AgwgACAEQQ9qNgIIIAAgAEEIaq1CgICAgNAEhDcDGCAAIACtQoCAgIDgBIQ3AxBBioDAACAAQRBqQdCGwAAQHAALIAYgAhAvAAsgACAEKQIANwIAIABBCGogBEEIaigCADYCACAEQRBqJAAL5wIBBX8CQCABQc3/e0EQIAAgAEEQTRsiAGtPDQAgAEEQIAFBC2pBeHEgAUELSRsiBGpBDGoQBiICRQ0AIAJBCGshAQJAIABBAWsiAyACcUUEQCABIQAMAQsgAkEEayIFKAIAIgZBeHEgAiADakEAIABrcUEIayICIABBACACIAFrQRBNG2oiACABayICayEDIAZBA3EEQCAAIAMgACgCBEEBcXJBAnI2AgQgACADaiIDIAMoAgRBAXI2AgQgBSACIAUoAgBBAXFyQQJyNgIAIAEgAmoiAyADKAIEQQFyNgIEIAEgAhAKDAELIAEoAgAhASAAIAM2AgQgACABIAJqNgIACwJAIAAoAgQiAUEDcUUNACABQXhxIgIgBEEQak0NACAAIAQgAUEBcXJBAnI2AgQgACAEaiIBIAIgBGsiBEEDcjYCBCAAIAJqIgIgAigCBEEBcjYCBCABIAQQCgsgAEEIaiEDCyADC4IDAQR/IAAoAgwhAgJAAkACQCABQYACTwRAIAAoAhghAwJAAkAgACACRgRAIABBFEEQIAAoAhQiAhtqKAIAIgENAUEAIQIMAgsgACgCCCIBIAI2AgwgAiABNgIIDAELIABBFGogAEEQaiACGyEEA0AgBCEFIAEiAkEUaiACQRBqIAIoAhQiARshBCACQRRBECABG2ooAgAiAQ0ACyAFQQA2AgALIANFDQICQCAAKAIcQQJ0QbyHwABqIgEoAgAgAEcEQCADKAIQIABGDQEgAyACNgIUIAINAwwECyABIAI2AgAgAkUNBAwCCyADIAI2AhAgAg0BDAILIAAoAggiACACRwRAIAAgAjYCDCACIAA2AggPC0HUisAAQdSKwAAoAgBBfiABQQN2d3E2AgAPCyACIAM2AhggACgCECIBBEAgAiABNgIQIAEgAjYCGAsgACgCFCIARQ0AIAIgADYCFCAAIAI2AhgPCw8LQdiKwABB2IrAACgCAEF+IAAoAhx3cTYCAAvEAgEEfyAAQgA3AhAgAAJ/QQAgAUGAAkkNABpBHyABQf///wdLDQAaIAFBJiABQQh2ZyIDa3ZBAXEgA0EBdGtBPmoLIgI2AhwgAkECdEG8h8AAaiEEQQEgAnQiA0HYisAAKAIAcUUEQCAEIAA2AgAgACAENgIYIAAgADYCDCAAIAA2AghB2IrAAEHYisAAKAIAIANyNgIADwsCQAJAIAEgBCgCACIDKAIEQXhxRgRAIAMhAgwBCyABQRkgAkEBdmtBACACQR9HG3QhBQNAIAMgBUEddkEEcWoiBCgCECICRQ0CIAVBAXQhBSACIQMgAigCBEF4cSABRw0ACwsgAigCCCIBIAA2AgwgAiAANgIIIABBADYCGCAAIAI2AgwgACABNgIIDwsgBEEQaiAANgIAIAAgAzYCGCAAIAA2AgwgACAANgIIC4gCAQZ/IAAoAggiBCECAn9BASABQYABSQ0AGkECIAFBgBBJDQAaQQNBBCABQYCABEkbCyIGIAAoAgAgBGtLBH8gACAEIAYQFSAAKAIIBSACCyAAKAIEaiECAkAgAUGAAU8EQCABQT9xQYB/ciEFIAFBBnYhAyABQYAQSQRAIAIgBToAASACIANBwAFyOgAADAILIAFBDHYhByADQT9xQYB/ciEDIAFB//8DTQRAIAIgBToAAiACIAM6AAEgAiAHQeABcjoAAAwCCyACIAU6AAMgAiADOgACIAIgB0E/cUGAf3I6AAEgAiABQRJ2QXByOgAADAELIAIgAToAAAsgACAEIAZqNgIIQQALiAIBBn8gACgCCCIEIQICf0EBIAFBgAFJDQAaQQIgAUGAEEkNABpBA0EEIAFBgIAESRsLIgYgACgCACAEa0sEfyAAIAQgBhAXIAAoAggFIAILIAAoAgRqIQICQCABQYABTwRAIAFBP3FBgH9yIQUgAUEGdiEDIAFBgBBJBEAgAiAFOgABIAIgA0HAAXI6AAAMAgsgAUEMdiEHIANBP3FBgH9yIQMgAUH//wNNBEAgAiAFOgACIAIgAzoAASACIAdB4AFyOgAADAILIAIgBToAAyACIAM6AAIgAiAHQT9xQYB/cjoAASACIAFBEnZBcHI6AAAMAQsgAiABOgAACyAAIAQgBmo2AghBAAv6AQIDfwF+IwBBMGsiAiQAIAEoAgBBgICAgHhGBEAgASgCDCEDIAJBLGoiBEEANgIAIAJCgICAgBA3AiQgAkEkakGcg8AAIAMoAgAiAygCACADKAIEEAkaIAJBIGogBCgCACIDNgIAIAIgAikCJCIFNwMYIAFBCGogAzYCACABIAU3AgALIAEpAgAhBSABQoCAgIAQNwIAIAJBEGoiAyABQQhqIgEoAgA2AgAgAUEANgIAIAIgBTcDCEEMQQQQOyIBRQRAQQRBDBA+AAsgASACKQMINwIAIAFBCGogAygCADYCACAAQZyFwAA2AgQgACABNgIAIAJBMGokAAuUAgECfyMAQSBrIgUkAEG4h8AAQbiHwAAoAgAiBkEBajYCAAJAAn9BACAGQQBIDQAaQQFBpIfAAC0AAA0AGkGkh8AAQQE6AABBoIfAAEGgh8AAKAIAQQFqNgIAQQILQf8BcSIGQQJHBEAgBkEBcUUNASAFQQhqIAAgASgCGBEAAAwBC0Gsh8AAKAIAIgZBAEgNAEGsh8AAIAZBAWo2AgBBsIfAACgCAARAIAUgACABKAIUEQAAIAUgBDoAHSAFIAM6ABwgBSACNgIYIAUgBSkDADcCEEGwh8AAKAIAIAVBEGpBtIfAACgCACgCFBEAAAtBrIfAAEGsh8AAKAIAQQFrNgIAQaSHwABBADoAACADRQ0AAAsAC5wBAQF/IwBBEGsiBiQAAkAgAQRAIAZBBGogASADIAQgBSACKAIQEQcAAkAgBigCBCICIAYoAgwiAU0EQCAGKAIIIQUMAQsgAkECdCECIAYoAgghAyABRQRAQQQhBSADIAIQOAwBCyADIAJBBCABQQJ0IgIQNSIFRQ0CCyAAIAE2AgQgACAFNgIAIAZBEGokAA8LEDwAC0EEIAIQLwALnAECAn8BfkEBIQdBBCEGAkAgBa0gA61+IghCIIhQRQRAQQAhAwwBCyAIpyIDQYCAgIB4IARrSwRAQQAhAwwBCwJAAkACfyABBEAgAiABIAVsIAQgAxA1DAELIANFBEAgBCEGDAILIAMgBBA7CyIGDQAgACAENgIEDAELIAAgBjYCBEEAIQcLQQghBgsgACAGaiADNgIAIAAgBzYCAAuHAQEBfyMAQRBrIgMkACACIAEgAmoiAUsEQEEAQQAQLwALIANBBGogACgCACICIAAoAgRBCCABIAJBAXQiAiABIAJLGyIBIAFBCE0bIgFBAUEBEBQgAygCBEEBRgRAIAMoAgggAygCDBAvAAsgAygCCCECIAAgATYCACAAIAI2AgQgA0EQaiQAC5wBAgN/AX4jAEEgayICJAAgASgCAEGAgICAeEYEQCABKAIMIQMgAkEcaiIEQQA2AgAgAkKAgICAEDcCFCACQRRqQZyDwAAgAygCACIDKAIAIAMoAgQQCRogAkEQaiAEKAIAIgM2AgAgAiACKQIUIgU3AwggAUEIaiADNgIAIAEgBTcCAAsgAEGchcAANgIEIAAgATYCACACQSBqJAAL8QEBBH8jAEEQayIDJAAgAiABIAJqIgFLBEBBAEEAEC8ACyADQQRqIQQgACgCBCEGAn9BCCABIAAoAgAiAkEBdCIFIAEgBUsbIgEgAUEITRsiBSIBQQBIBEBBASECQQAhAUEEDAELAn8CQAJ/IAIEQCAGIAJBASABEDUMAQsgAUUEQEEBIQIMAgsgAUEBEDsLIgINACAEQQE2AgRBAQwBCyAEIAI2AgRBAAshAkEICyAEaiABNgIAIAQgAjYCACADKAIEQQFGBEAgAygCCCADKAIMEC8ACyADKAIIIQEgACAFNgIAIAAgATYCBCADQRBqJAALjgEBAX8CQAJAIABBhAFPBEAgANBvJgFBgIfAACgCAA0CQYCHwABBfzYCACAAQZSHwAAoAgAiAUkNASAAIAFrIgBBjIfAACgCAE8NAUGIh8AAKAIAIABBAnRqQZCHwAAoAgA2AgBBkIfAACAANgIAQYCHwABBgIfAACgCAEEBajYCAAsPCwALQYyDwAAQIAALVAEBfwJAAkAgACgCACAAKAIIIgNrIAJJBEAgACADIAIQFSAAKAIIIQMMAQsgAkUNAQsgAkUNACAAKAIEIANqIAEgAvwKAAALIAAgAiADajYCCEEAC1QBAX8CQAJAIAAoAgAgACgCCCIDayACSQRAIAAgAyACEBcgACgCCCEDDAELIAJFDQELIAJFDQAgACgCBCADaiABIAL8CgAACyAAIAIgA2o2AghBAAtEAQJ/IAEoAgQhAiABKAIAIQNBCEEEEDsiAUUEQEEEQQgQPgALIAEgAjYCBCABIAM2AgAgAEGMhcAANgIEIAAgATYCAAveAQIBfwF+IwBBIGsiAyQAIAMgATYCECADIAA2AgwgA0EBOwEcIAMgAjYCGCADIANBDGo2AhQjAEEQayIBJAAgA0EUaiIAKQIAIQQgASAANgIMIAEgBDcCBCMAQRBrIgAkACABQQRqIgEoAgAiAigCBCIDQQFxBEAgAigCACECIAAgA0EBdjYCBCAAIAI2AgAgAEG0g8AAIAEoAgQgASgCCCIALQAIIAAtAAkQEgALIABBgICAgHg2AgAgACABNgIMIABB0IPAACABKAIEIAEoAggiAC0ACCAALQAJEBIACy4AAkAgAWlBAUcgAEGAgICAeCABa0tyDQAgAARAIAAgARA7IgFFDQELIAEPCwALPgAgACgCAEGAgICAeEcEQCABIAAoAgQgACgCCBAyDwsgASgCACABKAIEIAAoAgwoAgAiACgCACAAKAIEEAkLLQACQCADaUEBRyABQYCAgIB4IANrS3INACAAIAEgAyACEDUiAEUNACAADwsACywBAX8jAEEQayIBJAAgASABQQ9qrUKAgICAwASENwMAQY6AwAAgASAAEBwAC7wBAQR/IwBBEGsiAyQAIwBBIGsiAiQAIAIgATYCFCACIAA2AhAgAiACQRBqrUKAgICAEIQ3AxggAkEEaiACQRhqEAsgAQRAIAAgARA4CyACKAIIIQACQCACKAIEIgUgAigCDCIETQRAIAAhAQwBCyAERQRAQQEhASAAIAUQOAwBCyAAIAVBASAEEDUiAQ0AQQEgBBAvAAsgAyAENgIEIAMgATYCACACQSBqJAAgAygCACADKAIEIANBEGokAAvOBAILfwFvIwBBEGsiBiQAIwBBEGsiCCQAIAhBCGojAEEgayIEJAAgBCABNgIUIAQgADYCECAEIARBEGqtQoCAgIAQhDcDGCAEQQRqIARBGGoQCyAEKAIEIQkgBCgCCCILIAQoAgwQBSENAn8jAEEQayIHJAACQEGAh8AAKAIARQRAQYCHwABBfzYCAEGQh8AAKAIAIgJBjIfAACgCACIDRgRAAn8gAiACQYSHwAAoAgAiA0cNABrQb0GAASACIAJBgAFNGyIF/A8BIgNBf0YNAwJAQZSHwAAoAgAiDEUEQEGUh8AAIAM2AgAMAQsgAiAMaiADRw0ECyACQYSHwAAoAgAiAyACayAFTw0AGiAHQQRqIANBiIfAACgCACACIAVqIgNBBEEEEBQgBygCBEEBRg0DQYiHwAAgBygCCDYCAEGEh8AAIAM2AgBBjIfAACgCAAsiBSADTw0CQYiHwAAoAgAgBUECdGogAkEBajYCAEGMh8AAIAVBAWoiAzYCAAsgAiADTw0BQZCHwABBiIfAACgCACACQQJ0aigCADYCAEGAh8AAQYCHwAAoAgBBAWo2AgBBlIfAACgCACEDIAdBEGokACACIANqDAILQfyCwAAQIAsACyICIA0mASAEIAI2AhggCQRAIAsgCRA4CyAEQRhqKAIAJQEQAiACQYQBTwRAIAIQGAtBgIDAAEEKEABBgIDAAEEKEAFBADYCACAEQSBqJAAgAQRAIAAgARA4CyAGQgA3AgAgCEEQaiQAIAYoAgAgBigCBCAGQRBqJAALHQAgAEUEQBA8AAsgACACIAMgBCAFIAEoAhARCwALGwAgAEUEQBA8AAsgACACIAMgBCABKAIQEQwACxsAIABFBEAQPAALIAAgAiADIAQgASgCEBEFAAsbACAARQRAEDwACyAAIAIgAyAEIAEoAhAREgALGwAgAEUEQBA8AAsgACACIAMgBCABKAIQERQACxsAIABFBEAQPAALIAAgAiADIAQgASgCEBEWAAslAQF/IAAoAgAiAUGAgICAeHJBgICAgHhHBEAgACgCBCABEDgLCxkAIABFBEAQPAALIAAgAiADIAEoAhARBAALFwAgAEUEQBA8AAsgACACIAEoAhARAQALFwEBfyAAKAIAIgEEQCAAKAIEIAEQOAsLHwAgAEEIakGEhMAAKQIANwIAIABB/IPAACkCADcCAAsfACAAQQhqQfSDwAApAgA3AgAgAEHsg8AAKQIANwIACx0AIAAEQCAAIAEQPgALQayFwABBI0HAhcAAEBwACwwAIABB3QAgARAcAAsNACABBEAgACABEDgLCxYAIAAoAgAgASACIAAoAgQoAgwRAgALFAAgACgCACABIAAoAgQoAgwRAQALEAAgASAAKAIAIAAoAgQQCAvfBgEFfwJ/AkACQAJAAkACQAJAAkAgAEEEayIHKAIAIghBeHEiBEEEQQggCEEDcSIFGyABak8EQCAFQQAgAUEnaiIGIARJGw0BAkAgAkEJTwRAIAIgAxAMIgINAUEADAoLQQAhAiADQcz/e0sNCEEQIANBC2pBeHEgA0ELSRshASAAQQhrIQYgBUUEQCAGRSABQYACSXIgBCABa0GAgAhLIAEgBE9ycg0HIAAMCgsgBCAGaiEFAkAgASAESwRAIAVB6IrAACgCAEYNAUHkisAAKAIAIAVHBEAgBSgCBCIIQQJxDQkgCEF4cSIIIARqIgQgAUkNCSAFIAgQDSAEIAFrIgVBEE8EQCAHIAEgBygCAEEBcXJBAnI2AgAgASAGaiIBIAVBA3I2AgQgBCAGaiIEIAQoAgRBAXI2AgQgASAFEAoMCQsgByAEIAcoAgBBAXFyQQJyNgIAIAQgBmoiASABKAIEQQFyNgIEDAgLQdyKwAAoAgAgBGoiBCABSQ0IAkAgBCABayIFQQ9NBEAgByAIQQFxIARyQQJyNgIAIAQgBmoiASABKAIEQQFyNgIEQQAhBUEAIQEMAQsgByABIAhBAXFyQQJyNgIAIAEgBmoiASAFQQFyNgIEIAQgBmoiBCAFNgIAIAQgBCgCBEF+cTYCBAtB5IrAACABNgIAQdyKwAAgBTYCAAwHCyAEIAFrIgRBD00NBiAHIAEgCEEBcXJBAnI2AgAgASAGaiIBIARBA3I2AgQgBSAFKAIEQQFyNgIEIAEgBBAKDAYLQeCKwAAoAgAgBGoiBCABSw0EDAYLIAMgASABIANLGyIDBEAgAiAAIAP8CgAACyAHKAIAIgNBeHEiByABQQRBCCADQQNxIgMbakkNAiADRSAGIAdPcg0GQcyEwABB/ITAABAwAAtBjITAAEG8hMAAEDAAC0HMhMAAQfyEwAAQMAALQYyEwABBvITAABAwAAsgByABIAhBAXFyQQJyNgIAIAEgBmoiBSAEIAFrIgFBAXI2AgRB4IrAACABNgIAQeiKwAAgBTYCAAsgBkUNACAADAMLIAMQBiIBRQ0BIANBfEF4IAcoAgAiAkEDcRsgAkF4cWoiAiACIANLGyICBEAgASAAIAL8CgAACyABIQILIAAQBwsgAgsLEwAgAEGMhcAANgIEIAAgATYCAAsQACABIAAoAgAgACgCBBAyC1sBAn8CQAJAIABBBGsoAgAiAkF4cSIDQQRBCCACQQNxIgIbIAFqTwRAIAJBACADIAFBJ2pLGw0BIAAQBwwCC0GMhMAAQbyEwAAQMAALQcyEwABB/ITAABAwAAsLDwAgAEGcg8AAIAEgAhAJCw8AIABB0IXAACABIAIQCQsZAAJ/IAFBCU8EQCABIAAQDAwBCyAAEAYLCwwAQceCwABBMhADAAsMACAAIAEpAgA3AwALPQEBfyMAQRBrIgIkACACIAE2AgwgAiAANgIIIAJBCGoiACgCACAAKAIEQaiHwAAoAgAiAEEPIAAbEQAAAAsNACABQeCGwABBBRAyCw0AIAFB5YbAAEEYEAgLDABBgIvAAEEBOgAACwkAIABBADYCAAsLjgcDAEGAgMAAC+UFdGVzdCBsYWJlbMACOiDAAC9ydXN0Yy80NzQyNzY5NjFmNDhiMGQwNWY0ZWEyNjBiYTQwMDA5NmIwMjc1ODRlL2xpYnJhcnkvYWxsb2Mvc3JjL2ZtdC5ycwBDOlxVc2Vyc1w5XC5jYXJnb1xyZWdpc3RyeVxzcmNcaW5kZXguY3JhdGVzLmlvLTE5NDljZjhjNmI1YjU1N2Zcd2FzbS1iaW5kZ2VuLTAuMi4xMDhcc3JjXGV4dGVybnJlZi5ycwAvcnVzdGMvNDc0Mjc2OTYxZjQ4YjBkMDVmNGVhMjYwYmE0MDAwOTZiMDI3NTg0ZS9saWJyYXJ5L2FsbG9jL3NyYy9yYXdfdmVjL21vZC5ycwAvcnVzdC9kZXBzL2RsbWFsbG9jLTAuMi4xMS9zcmMvZGxtYWxsb2MucnMAB0hlbGxvLCDAASEAY2xvc3VyZSBpbnZva2VkIHJlY3Vyc2l2ZWx5IG9yIGFmdGVyIGJlaW5nIGRyb3BwZWQAAABZABAAZQAAAH8AAAARAAAAWQAQAGUAAACMAAAAEQAAABAAAAAMAAAABAAAABEAAAASAAAAEwAAAAAAAAAIAAAABAAAABQAAAAVAAAAFgAAABcAAAAYAAAAEAAAAAQAAAAZAAAAGgAAABsAAAAcAAAAbV3L1ixQ62N4QaZXcRuLuXVupikRacz0LouIORGvEjVhc3NlcnRpb24gZmFpbGVkOiBwc2l6ZSA+PSBzaXplICsgbWluX292ZXJoZWFkAAAQARAAKgAAALEEAAAJAAAAYXNzZXJ0aW9uIGZhaWxlZDogcHNpemUgPD0gc2l6ZSArIG1heF9vdmVyaGVhZAAAEAEQACoAAAC3BAAADQAAAAAAAAAIAAAABAAAAB0AAAAQAAAADAAAAAQAAAAeAAAAY2FwYWNpdHkgb3ZlcmZsb3cAAAC/ABAAUAAAABwAAAAFAAAAHwAAAAwAAAAEAAAAIAAAACEAAAAiAEHwhcAAC40BAQAAACMAAABhIGZvcm1hdHRpbmcgdHJhaXQgaW1wbGVtZW50YXRpb24gcmV0dXJuZWQgYW4gZXJyb3Igd2hlbiB0aGUgdW5kZXJseWluZyBzdHJlYW0gZGlkIG5vdAAAEAAQAEgAAACKAgAADgAAAEVycm9yUmVmQ2VsbCBhbHJlYWR5IGJvcnJvd2VkAEGIh8AACwEEAIQBCXByb2R1Y2VycwIIbGFuZ3VhZ2UBBFJ1c3QADHByb2Nlc3NlZC1ieQMFcnVzdGMlMS45NS4wLW5pZ2h0bHkgKDQ3NDI3Njk2MSAyMDI2LTAxLTI2KQZ3YWxydXMGMC4yNC40DHdhc20tYmluZGdlbhMwLjIuMTA4IChhNzg4ZjU4ZjkpAGsPdGFyZ2V0X2ZlYXR1cmVzBisPbXV0YWJsZS1nbG9iYWxzKxNub250cmFwcGluZy1mcHRvaW50KwtidWxrLW1lbW9yeSsIc2lnbi1leHQrD3JlZmVyZW5jZS10eXBlcysKbXVsdGl2YWx1ZQ==";

    // 3. ВСПОМОГАТЕЛЬНАЯ ФУНКЦИЯ (Base64 -> Uint8Array)
    function base64ToUint8Array(base64) {
        const binary_string = window.atob(base64);
        const len = binary_string.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes;
    }

    // 4. ЗАПУСК
    async function run() {
        // Декодируем байты
        const wasmBytes = base64ToUint8Array(WASM_BASE64);

        // Инициализируем wasm-bindgen, передавая байты напрямую
        // Обратите внимание: при target no-modules функция называется wasm_bindgen
        await wasm_bindgen(wasmBytes);

        console.log("Wasm loaded!");

        // Теперь можно вызывать ваши функции
        // Они доступны как методы объекта wasm_bindgen
        wasm_bindgen.greet_and_log("Tampermonkey User");

        // Или так:
        let msg = wasm_bindgen.greet("World");
        console.log("Result from Rust:", msg);
    }

    run();
})();